import type { GameContent } from './types';

/** English. */
export default {
  chapters: {
    1: 'What lies behind home',
    2: 'Neighbours and rumours',
    3: 'What the water keeps',
    4: 'Towards the stars',
  },
  places: {
    'bosque-musgo': {
      name: 'Moss Forest',
      the: 'the Moss Forest',
      from: 'from the Moss Forest',
      caption: 'Everything is soft here. Even the silence.',
      quote: 'I took a nap without meaning to.',
      stories: [
        'The moss was so soft that I took a nap without meaning to. When I woke up, someone had tucked me in with a leaf.',
        'The trees here speak very softly, almost in whispers. I think one of them said "welcome", but it might have been the wind.',
        'I found a little trail of golden dust between the roots. I followed it for a while, but it vanished right where it started getting dark. Strange, isn’t it?',
      ],
    },
    'pradera-suave': {
      name: 'Gentle Meadow',
      the: 'the Gentle Meadow',
      from: 'from the Gentle Meadow',
      caption: 'Grass up to my ears and zero hurry.',
      quote: 'I saved you a clover.',
      stories: [
        'I spent the afternoon looking for a four-leaf clover. I found a very friendly three-leaf one and decided that was enough. I saved it for you.',
        'I rolled down the hill six times. On the seventh I got a little dizzy, so I lay down to watch the clouds go by.',
        'There were strawberries hiding under the leaves, as if they were playing hide-and-seek. I won. Well, and I ate a couple.',
      ],
    },
    'dientes-de-leon': {
      name: 'Dandelion Hill',
      the: 'Dandelion Hill',
      from: 'from Dandelion Hill',
      caption: 'Every puff is a tiny wish.',
      quote: 'I made friends with a puff of wind.',
      stories: [
        'I blew on a dandelion and its seeds flew off in a line, very properly. One stayed with me. I made friends with a puff of wind.',
        'From the top of the hill you can see our house. I waved at you with my light, just in case you were looking out of the window.',
        'At night, on the hilltop, I saw a little light cross the sky and fall behind the forest. It made no sound. I really wanted to know where it went.',
      ],
    },
    'jardin-setas': {
      name: 'Mushroom Garden',
      the: 'the Mushroom Garden',
      from: 'from the Mushroom Garden',
      caption: 'Mushrooms the size of umbrellas. And of thimbles.',
      quote: 'A mushroom winked at me. I think.',
      stories: [
        'A mushroom winked at me. I think. I winked back, to be polite, and it blushed even redder.',
        'It started drizzling, so I sheltered under the biggest mushroom. Three beetles were already there playing cards. They let me watch.',
        'The mushrooms here glow a little at night, like me. We spent a while glowing together and it was lovely.',
      ],
    },
    'lago-lunas': {
      name: 'Lake of Moons',
      the: 'the Lake of Moons',
      from: 'from the Lake of Moons',
      caption: 'One moon above, another below. And me in the middle.',
      quote: 'There were two moons and neither was made of cheese.',
      stories: [
        'There were two moons and neither was made of cheese. I checked. The one below melted into ripples every time I touched it.',
        'I skipped a flat stone across the water: one, two, three times. On the fourth it sank, but with great dignity.',
        'Tonight the lake reflected three moons, and there were only two in the sky. I stayed very still watching the third one until it faded.',
      ],
    },
    'madriguera-vecino': {
      name: 'Neighbour’s Burrow',
      the: 'the Neighbour’s Burrow',
      from: 'from the Neighbour’s Burrow',
      caption: 'It smells of toast and good earth.',
      quote: 'He had biscuits. Say no more.',
      stories: [
        'The neighbour is a mole with glasses who can barely see but cooks wonderfully. He had biscuits. Say no more.',
        'He showed me his button collection: one hundred and twelve, and not a single pair. He says the others will turn up one day.',
        'Over tea he told me that a few nights ago he heard something fall in the forest, "like a little bell that tripped". Then he changed the subject, but I kept thinking about it.',
      ],
    },
    'nube-baja': {
      name: 'Low Cloud',
      the: 'the Low Cloud',
      from: 'from the Low Cloud',
      caption: 'A cloud that decided to live on the ground.',
      quote: 'It was soft and a little damp.',
      stories: [
        'The cloud was soft and a little damp. I sank in up to my ears and came out with my hair, well, my light, all curly.',
        'You can’t see anything inside the cloud, so I played guessing shapes with my eyes closed. I always won, because nobody could say I was wrong.',
        'The cloud told me it doesn’t want to go up to the sky because it’s very windy up there. I told it that it’s very nice down here too. I think it liked that.',
      ],
    },
    'puente-raices': {
      name: 'Root Bridge',
      the: 'the Root Bridge',
      from: 'from the Root Bridge',
      caption: 'A bridge that grew all by itself, in no hurry.',
      quote: 'I tiptoed across so as not to wake it.',
      stories: [
        'The bridge is made of roots that held hands many, many years ago. I tiptoed across so as not to wake it.',
        'Halfway across there was a hedgehog stuck between two roots. I gave it a gentle push and it rolled out, very dignified, as if nothing had happened.',
        'Caught on a root I found a letter with no return address. It only said: "For whoever finds the golden path". Could it be for me?',
      ],
    },
    'cuevas-cristal': {
      name: 'Crystal Caves',
      the: 'the Crystal Caves',
      from: 'from the Crystal Caves',
      caption: 'Every time I glow, the cave glows with me.',
      quote: 'My light bounced everywhere.',
      stories: [
        'Inside the cave my light bounced everywhere. For a moment I thought there were a hundred Lampis, and I felt a little shy.',
        'Little soot sprites live in the dark corners. At first they hid, but when I sat still they came to warm up with me.',
        'On the deepest wall there’s a very old drawing: a star with a little face, falling. Someone painted it long ago. Or maybe not that long ago.',
      ],
    },
    'faro-dormido': {
      name: 'Sleeping Lighthouse',
      the: 'the Sleeping Lighthouse',
      from: 'from the Sleeping Lighthouse',
      caption: 'A lighthouse that switched off to take a nap.',
      quote: 'I lent it my light for a while.',
      stories: [
        'The lighthouse has been asleep for years and snores a little when the wind blows. I lent it my light for a while and it blinked, as if it were dreaming something nice.',
        'I climbed the hundred and forty steps. At the top lives a little owl who takes care of everything while the lighthouse sleeps. He was exhausted, so I kept him company.',
        'With the lighthouse telescope you can see very far. I saw an island with an enormous stopped clock, and a paper boat sailing towards it.',
      ],
    },
    'charca-ranas': {
      name: 'Pond of the Singing Frogs',
      the: 'the Pond of the Singing Frogs',
      from: 'from the Pond of the Singing Frogs',
      caption: 'The choir rehearses here every night.',
      quote: 'They let me sing the C. Only the C.',
      stories: [
        'The frogs have a choir and they let me sing the C. Only the C. I sang it with a lot of feeling.',
        'One very small frog always sang the wrong note and the others gave her funny looks. To me she was the best singer.',
        'The frogs say that water remembers everything it has reflected. I asked them about the third moon and all forty of them went quiet at once.',
      ],
    },
    'cascada-timida': {
      name: 'Shy Waterfall',
      the: 'the Shy Waterfall',
      from: 'from the Shy Waterfall',
      caption: 'It only falls when it thinks nobody is looking.',
      quote: 'I turned around and it started falling.',
      stories: [
        'The waterfall only falls when nobody is looking. I turned around and it started falling, very happily. I caught it out of the corner of my eye, but I didn’t say a thing.',
        'Behind the water there’s a tiny cave with snails who collect drops. They gave me one. I thought it was a lovely gesture.',
        'At the foot of the waterfall, between the stones, a little golden dust was shining. The same as in the forest. The path goes on, towards the sea.',
      ],
    },
    'playa-conchas': {
      name: 'Seashell Beach',
      the: 'Seashell Beach',
      from: 'from Seashell Beach',
      caption: 'Warm sand and waves in no hurry.',
      quote: 'A wave brought me a shell and left.',
      stories: [
        'A wave brought me a shell and ran off, as if it were embarrassed. It came straight back to see if I liked it.',
        'A crab challenged me to a sideways race. I lost, of course, because I float. He said that was cheating, but we laughed a lot.',
        'I built a sandcastle with a tower and everything. The tide took it away very gently, almost asking permission.',
      ],
    },
    'muelle-barcas': {
      name: 'Paper Boat Pier',
      the: 'the Paper Boat Pier',
      from: 'from the Paper Boat Pier',
      caption: 'Every boat carries a message inside.',
      quote: 'I folded a boat and wrote your name on it.',
      stories: [
        'Here people fold paper boats and set them free with a message. I folded one and wrote your name on it. We’ll see where it ends up.',
        'A little fish popped its head up every time a boat passed, to read the messages. Very nosy, but very sweet.',
        'A boat came back to the pier in the same handwriting as the letter on the bridge: "Almost there. Look up". It gave me a lovely shiver.',
      ],
    },
    'isla-reloj': {
      name: 'Island of the Stopped Clock',
      the: 'the Island of the Stopped Clock',
      from: 'from the Island of the Stopped Clock',
      caption: 'Here it is always a quarter past eleven.',
      quote: 'Nobody is ever late for anything here.',
      stories: [
        'On this island it is always a quarter past eleven, so nobody is ever late for anything. I took the afternoon very, very easy.',
        'The island crabs take turns winding the clock, even though it doesn’t move. They say it’s just in case, which seems very sensible to me.',
        'The clock stopped the same night the little light fell. I gave it a tap and the hands trembled, as if they wanted to point at something in the sky.',
      ],
    },
    'mercadillo-buhos': {
      name: 'Owls’ Night Market',
      the: 'the Owls’ Night Market',
      from: 'from the Owls’ Night Market',
      caption: 'Opens at midnight. You pay with stories.',
      quote: 'I paid for a map with one of your stories.',
      stories: [
        'At this market nothing is paid for with money, only with stories. I paid for a map with one of your stories. I hope you don’t mind.',
        'A very serious owl sells loose cogs and won’t say what they’re for. He winked at me, so it must be something important.',
        'The map I bought has an X drawn at the top of the mountain, next to a little star. It looks like we’re nearly there.',
      ],
    },
    'tejados-aldea': {
      name: 'Rooftops of the Sleeping Village',
      the: 'the Rooftops of the Sleeping Village',
      from: 'from the Rooftops of the Sleeping Village',
      caption: 'Cosy chimneys and philosopher cats.',
      quote: 'I strolled from chimney to chimney.',
      stories: [
        'I strolled from chimney to chimney, warming my tummy. A cat explained to me that night is for thinking. Then he fell asleep.',
        'On a washing line there were socks of every colour and not a single pair. It reminded me of the neighbour and his buttons. Something funny is going on with pairs around here.',
        'From the highest rooftop you could see the mountain. There was a light at the top, tiny and trembling, like someone waiting to be found.',
      ],
    },
    'montana-manta': {
      name: 'Blanket Mountain',
      the: 'Blanket Mountain',
      from: 'from Blanket Mountain',
      caption: 'The snow here keeps you warm instead of cold.',
      quote: 'The snow was warm. I promise.',
      stories: [
        'The snow on this mountain was warm. I promise. I made a snowman and he thanked me with a very soft hug.',
        'I climbed slowly, with lots of stops to look at the view. Well, and to rest. Mostly to rest.',
        'Near the top I found tiny star-shaped footprints. They led to a garden hidden in the clouds. Tomorrow, if I glow, I’ll go.',
      ],
    },
    'jardin-estrellas': {
      name: 'Garden of Fallen Stars',
      the: 'the Garden of Fallen Stars',
      from: 'from the Garden of Fallen Stars',
      caption: 'Where fallen stars come to rest.',
      quote: 'I found her. And she found me too.',
      stories: [
        'At last I found her: a small little star, sitting among moonflowers. She had fallen and was too shy to go back. I told her it happens to me too, and she laughed.',
        'The letters, the boats, the golden dust: it was her, leaving clues in case someone was looking for her. And I was. I found her, and she found me too.',
        'Today we spent the day glowing together in the garden. She says she’s in no hurry to go back up to the sky, that it’s very nice down here. I told her about you.',
      ],
    },
    'observatorio-cometas': {
      name: 'Comet Observatory',
      the: 'the Comet Observatory',
      from: 'from the Comet Observatory',
      caption: 'An old dome that still looks up.',
      quote: 'I counted comets until I fell asleep.',
      stories: [
        'The observatory is abandoned, but the telescope still points at the sky out of habit. I counted comets until I fell asleep.',
        'A stargazing owl writes the stars down in a notebook. He showed me a gap in a constellation: one is missing, a tiny one. He says she’ll come back when she wants to.',
        'I fixed the dome with a cog from the market. It opened with a very long creak and so much light came in that it looked like daytime.',
      ],
    },
  },
  items: {
    piedra: { name: 'Smooth stone', a: 'a smooth stone', feminine: false },
    semilla: { name: 'Flying seed', a: 'a flying seed', feminine: false },
    trebol: { name: 'Clover', a: 'a clover', feminine: false },
    seta: {
      name: 'Glowing mushroom',
      a: 'a glowing mushroom',
      feminine: false,
    },
    cristal: { name: 'Little crystal', a: 'a little crystal', feminine: false },
    farolillo: { name: 'Paper lantern', a: 'a paper lantern', feminine: false },
    bellota: {
      name: 'Acorn with a hat',
      a: 'an acorn with a hat',
      feminine: false,
    },
    pluma: { name: 'Owl feather', a: 'an owl feather', feminine: false },
    hoja: { name: 'Golden leaf', a: 'a golden leaf', feminine: false },
    concha: { name: 'Pink shell', a: 'a pink shell', feminine: false },
    gota: { name: 'Dewdrop', a: 'a dewdrop', feminine: false },
    llave: { name: 'Tiny key', a: 'a tiny key', feminine: false },
    boton: { name: 'Lost button', a: 'a lost button', feminine: false },
    galleta: { name: 'Oat biscuit', a: 'an oat biscuit', feminine: false },
    taza: {
      name: 'Cup without a handle',
      a: 'a cup without a handle',
      feminine: false,
    },
    barquito: { name: 'Paper boat', a: 'a paper boat', feminine: false },
    canica: { name: 'Water marble', a: 'a water marble', feminine: false },
    campanilla: { name: 'Bluebell', a: 'a bluebell', feminine: false },
    'flor-luna': { name: 'Moonflower', a: 'a moonflower', feminine: false },
    fresa: { name: 'Wild strawberry', a: 'a wild strawberry', feminine: false },
    ovillo: { name: 'Ball of wool', a: 'a ball of wool', feminine: false },
    mapa: { name: 'Crumpled map', a: 'a crumpled map', feminine: false },
    carta: {
      name: 'Letter with no sender',
      a: 'a letter with no sender',
      feminine: false,
    },
    reloj: { name: 'Pocket watch', a: 'a pocket watch', feminine: false },
    engranaje: { name: 'Cog', a: 'a cog', feminine: false },
    vela: { name: 'Wax candle', a: 'a wax candle', feminine: false },
    catalejo: { name: 'Spyglass', a: 'a spyglass', feminine: false },
    'polvo-estrella': {
      name: 'Jar of stardust',
      a: 'a jar of stardust',
      feminine: false,
    },
    'trocito-luna': {
      name: 'Piece of moon',
      a: 'a piece of moon',
      feminine: false,
    },
    pina: { name: 'Pinecone', a: 'a pinecone', feminine: false },
    geoda: { name: 'Geode', a: 'a geode', feminine: false },
    nenufar: { name: 'Water lily', a: 'a water lily', feminine: false },
    bufanda: { name: 'Tiny scarf', a: 'a tiny scarf', feminine: false },
    moneda: { name: 'Old coin', a: 'an old coin', feminine: false },
    calcetin: { name: 'Odd sock', a: 'an odd sock', feminine: false },
    burbuja: {
      name: 'Bubble that never pops',
      a: 'a bubble that never pops',
      feminine: false,
    },
  },
  friends: {
    musguito: { name: 'Mossy', a: 'Mossy', feminine: false },
    hollin: { name: 'Sooty', a: 'Sooty', feminine: false },
    nubecilla: { name: 'Cloudlet', a: 'Cloudlet', feminine: false },
    chispin: { name: 'Sparky', a: 'Sparky', feminine: false },
    topito: { name: 'Moley', a: 'Moley', feminine: false },
    pinchito: { name: 'Prickles', a: 'Prickles', feminine: false },
    ranita: { name: 'Froggy Do', a: 'Froggy Do', feminine: false },
    caracolina: { name: 'Shelly', a: 'Shelly', feminine: false },
    burbujo: { name: 'Bubbles', a: 'Bubbles', feminine: false },
    pinzas: { name: 'Pinchy', a: 'Pinchy', feminine: false },
    mochuelito: { name: 'Owlet', a: 'Owlet', feminine: false },
    estrellita: { name: 'Starlet', a: 'Starlet', feminine: false },
  },
} satisfies GameContent;
