import type { GameContent } from './types';

/** Español: el texto original. */
export default {
  chapters: {
    '1': 'Lo que hay detrás de casa',
    '2': 'Vecinos y rumores',
    '3': 'Lo que guarda el agua',
    '4': 'Hacia las estrellas',
  },
  places: {
    'bosque-musgo': {
      name: 'Bosque de Musgo',
      the: 'el Bosque de Musgo',
      from: 'del Bosque de Musgo',
      caption: 'Aquí todo es blandito. Hasta el silencio.',
      quote: 'Me eché una siesta sin querer.',
      stories: [
        'El musgo estaba tan blandito que me eché una siesta sin querer. Cuando me desperté, alguien me había tapado con una hoja.',
        'Los árboles de aquí hablan muy bajito, casi en susurros. Creo que uno me dijo «bienvenida», pero igual era el viento.',
        'Encontré un caminito de polvo dorado entre las raíces. Lo seguí un rato, pero se perdía justo donde empezaba a oscurecer. Qué raro, ¿no?',
      ],
    },
    'pradera-suave': {
      name: 'Pradera Suave',
      the: 'la Pradera Suave',
      from: 'de la Pradera Suave',
      caption: 'Hierba hasta las orejas y cero prisas.',
      quote: 'Te guardé un trébol.',
      stories: [
        'Me pasé la tarde buscando un trébol de cuatro hojas. Encontré uno de tres muy simpático y me pareció suficiente. Te lo he guardado.',
        'Rodé cuesta abajo seis veces. La séptima me mareé un poquito, así que me tumbé a mirar cómo pasaban las nubes.',
        'Había fresas escondidas debajo de las hojas, como si jugaran al escondite. Gané yo. Bueno, y alguna me comí.',
      ],
    },
    'dientes-de-leon': {
      name: 'Colina de los Dientes de León',
      the: 'la Colina de los Dientes de León',
      from: 'de la Colina de los Dientes de León',
      caption: 'Cada soplido es un deseo pequeñito.',
      quote: 'Me hice amiga de un soplido.',
      stories: [
        'Soplé un diente de león y sus semillas se fueron volando en fila, muy formales. Una se quedó conmigo. Me hice amiga de un soplido.',
        'Desde lo alto de la colina se ve nuestra casa. Te saludé con la luz, por si acaso mirabas por la ventana.',
        'Por la noche, en la cima, vi una lucecita cruzar el cielo y caer detrás del bosque. No hizo ruido. Me quedé con ganas de saber adónde fue.',
      ],
    },
    'jardin-setas': {
      name: 'Jardín de Setas',
      the: 'el Jardín de Setas',
      from: 'del Jardín de Setas',
      caption: 'Setas del tamaño de paraguas. Y de dedales.',
      quote: 'Una seta me guiñó un ojo. Creo.',
      stories: [
        'Una seta me guiñó un ojo. Creo. Le guiñé yo también, por educación, y se puso más colorada todavía.',
        'Empezó a chispear y me refugié debajo de la seta más grande. Allí ya había tres escarabajos jugando a las cartas. Me dejaron mirar.',
        'Las setas de aquí brillan un poco por la noche, como yo. Estuvimos un rato brillando juntas y fue muy agradable.',
      ],
    },
    'lago-lunas': {
      name: 'Lago de las Lunas',
      the: 'el Lago de las Lunas',
      from: 'del Lago de las Lunas',
      caption: 'Una luna arriba, otra abajo. Y yo en medio.',
      quote: 'Había dos lunas y ninguna era de queso.',
      stories: [
        'Había dos lunas y ninguna era de queso. Lo comprobé. La de abajo se deshacía en ondas cada vez que la tocaba.',
        'Hice saltar una piedra lisa sobre el agua: una, dos, tres veces. A la cuarta se hundió, pero con mucha dignidad.',
        'Esta noche el lago reflejaba tres lunas, y en el cielo solo había dos. Me quedé muy quieta mirando la tercera hasta que se apagó.',
      ],
    },
    'madriguera-vecino': {
      name: 'Madriguera del Vecino',
      the: 'la Madriguera del Vecino',
      from: 'de la Madriguera del Vecino',
      caption: 'Huele a pan tostado y a tierra buena.',
      quote: 'Tenía galletas. No te digo más.',
      stories: [
        'El vecino es un topo con gafas que ve fatal pero cocina de maravilla. Tenía galletas. No te digo más.',
        'Me enseñó su colección de botones: ciento doce, y ninguno hace pareja. Dice que algún día aparecerán los otros.',
        'Mientras merendábamos me contó que hace unas noches oyó algo caer en el bosque, «como una campanilla que se tropieza». Luego cambió de tema, pero yo me quedé pensando.',
      ],
    },
    'nube-baja': {
      name: 'Nube Baja',
      the: 'la Nube Baja',
      from: 'de la Nube Baja',
      caption: 'Una nube que se quedó a vivir en el suelo.',
      quote: 'Estaba blandita y un poco mojada.',
      stories: [
        'La nube estaba blandita y un poco mojada. Me hundí hasta las orejas y salí con el pelo, bueno, la luz, toda rizada.',
        'Dentro de la nube no se ve nada, así que jugué a adivinar formas con los ojos cerrados. Gané siempre, porque nadie podía llevarme la contraria.',
        'La nube me contó que no quiere subir al cielo porque allí arriba hay mucho viento. Yo le dije que abajo también se está muy bien. Creo que le gustó.',
      ],
    },
    'puente-raices': {
      name: 'Puente de Raíces',
      the: 'el Puente de Raíces',
      from: 'del Puente de Raíces',
      caption: 'Un puente que creció solo, sin prisa.',
      quote: 'Crucé de puntillas para no despertarlo.',
      stories: [
        'El puente está hecho de raíces que se dieron la mano hace muchísimos años. Crucé de puntillas para no despertarlo.',
        'A mitad del puente había un erizo atascado entre dos raíces. Lo empujé con cuidado y salió rodando, muy digno, como si no hubiera pasado nada.',
        'Enganchada en una raíz encontré una carta sin remite. Solo ponía: «Para quien encuentre el camino dorado». ¿Será para mí?',
      ],
    },
    'cuevas-cristal': {
      name: 'Cuevas de Cristal',
      the: 'las Cuevas de Cristal',
      from: 'de las Cuevas de Cristal',
      caption: 'Cada vez que brillo, la cueva brilla conmigo.',
      quote: 'Mi luz rebotaba por todas partes.',
      stories: [
        'Dentro de la cueva mi luz rebotaba por todas partes. Por un momento pensé que éramos cien Lumis, y me dio un poco de vergüenza.',
        'Unos bichitos de hollín viven en los rincones oscuros. Al principio se escondieron, pero cuando me senté quieta vinieron a calentarse conmigo.',
        'En la pared más honda hay un dibujo muy antiguo: una estrella con carita, cayendo. Alguien lo pintó hace mucho. O a lo mejor no hace tanto.',
      ],
    },
    'faro-dormido': {
      name: 'Faro Dormido',
      the: 'el Faro Dormido',
      from: 'del Faro Dormido',
      caption: 'Un faro que se apagó para echarse la siesta.',
      quote: 'Le presté mi luz un ratito.',
      stories: [
        'El faro lleva años dormido y ronca un poco cuando sopla el viento. Le presté mi luz un ratito y parpadeó, como si soñara algo bonito.',
        'Subí los ciento cuarenta escalones. Arriba vive un mochuelo que se encarga de todo mientras el faro duerme. Estaba agotado y le hice compañía.',
        'Con el catalejo del faro se ve muy lejos. Vi una isla con un reloj enorme, parado, y un barco de papel navegando hacia ella.',
      ],
    },
    'charca-ranas': {
      name: 'Charca de las Ranas Cantoras',
      the: 'la Charca de las Ranas Cantoras',
      from: 'de la Charca de las Ranas Cantoras',
      caption: 'Aquí se ensaya el coro todas las noches.',
      quote: 'Me dejaron cantar el do. Solo el do.',
      stories: [
        'Las ranas tienen un coro y me dejaron cantar el do. Solo el do. Lo hice con mucho sentimiento.',
        'Una rana muy pequeña se equivocaba siempre de nota y las demás la miraban raro. A mí me pareció la que mejor cantaba.',
        'Dicen las ranas que el agua recuerda todo lo que ha reflejado. Les pregunté por la tercera luna y se callaron las cuarenta a la vez.',
      ],
    },
    'cascada-timida': {
      name: 'Cascada Tímida',
      the: 'la Cascada Tímida',
      from: 'de la Cascada Tímida',
      caption: 'Solo cae cuando cree que nadie la mira.',
      quote: 'Me di la vuelta y se puso a caer.',
      stories: [
        'La cascada solo cae cuando nadie la mira. Me di la vuelta y se puso a caer, muy contenta. La pillé de reojo, pero no le dije nada.',
        'Detrás del agua hay una cuevecita con caracoles que coleccionan gotas. Me regalaron una. Me pareció un gesto precioso.',
        'Al pie de la cascada, entre las piedras, brillaba un poquito de polvo dorado. El mismo del bosque. El camino sigue, y va hacia el mar.',
      ],
    },
    'playa-conchas': {
      name: 'Playa de las Conchas',
      the: 'la Playa de las Conchas',
      from: 'de la Playa de las Conchas',
      caption: 'Arena tibia y olas que no tienen prisa.',
      quote: 'Una ola me trajo una concha y se fue.',
      stories: [
        'Una ola me trajo una concha y se fue corriendo, como si le diera vergüenza. Volvió enseguida a ver si me había gustado.',
        'Un cangrejo me retó a correr de lado. Perdí, claro, porque yo floto. Me dijo que eso era trampa, pero nos reímos mucho.',
        'Hice un castillo de arena con torre y todo. La marea se lo llevó con mucha delicadeza, casi pidiendo permiso.',
      ],
    },
    'muelle-barcas': {
      name: 'Muelle de las Barcas de Papel',
      the: 'el Muelle de las Barcas de Papel',
      from: 'del Muelle de las Barcas de Papel',
      caption: 'Cada barca lleva un mensaje dentro.',
      quote: 'Doblé una barca y le puse tu nombre.',
      stories: [
        'Aquí la gente dobla barcas de papel y las suelta con un mensaje. Doblé una y le puse tu nombre. Ya verás tú adónde llega.',
        'Un pececito asomaba la cabeza cada vez que pasaba una barca, para leer los mensajes. Es muy cotilla, pero muy simpático.',
        'Una barca volvió al muelle con la misma letra que la carta del puente: «Ya casi. Mira hacia arriba». Me dio un escalofrío bonito.',
      ],
    },
    'isla-reloj': {
      name: 'Isla del Reloj Parado',
      the: 'la Isla del Reloj Parado',
      from: 'de la Isla del Reloj Parado',
      caption: 'Aquí siempre son las once y cuarto.',
      quote: 'Aquí nadie llega tarde a nada.',
      stories: [
        'En esta isla siempre son las once y cuarto, así que aquí nadie llega tarde a nada. Me tomé la tarde con muchísima calma.',
        'Los cangrejos de la isla dan cuerda al reloj por turnos, aunque no se mueva. Dicen que es por si acaso, y me parece muy sensato.',
        'El reloj se paró la misma noche en que cayó la lucecita. Le di un toquecito y las agujas temblaron, como si quisieran señalar algo del cielo.',
      ],
    },
    'mercadillo-buhos': {
      name: 'Mercadillo de los Búhos',
      the: 'el Mercadillo de los Búhos',
      from: 'del Mercadillo de los Búhos',
      caption: 'Abre a medianoche. Se paga con cuentos.',
      quote: 'Pagué un mapa con un cuento tuyo.',
      stories: [
        'En este mercadillo nada se paga con dinero, solo con cuentos. Pagué un mapa con un cuento tuyo. Espero que no te importe.',
        'Un búho muy serio vende engranajes sueltos y no quiere decir para qué sirven. Me guiñó un ojo, así que debe de ser algo importante.',
        'El mapa que compré tiene una equis dibujada en lo alto de la montaña, al lado de una estrellita. Tiene pinta de que ya queda poco.',
      ],
    },
    'tejados-aldea': {
      name: 'Tejados de la Aldea Dormida',
      the: 'los Tejados de la Aldea Dormida',
      from: 'de los Tejados de la Aldea Dormida',
      caption: 'Chimeneas calentitas y gatos filósofos.',
      quote: 'Paseé de chimenea en chimenea.',
      stories: [
        'Paseé de chimenea en chimenea, calentándome la barriguita. Un gato me explicó que la noche es para pensar. Luego se durmió.',
        'En un tendedero había calcetines de todos los colores y ninguno emparejado. Me acordé del vecino y sus botones. Algo pasa con las parejas por aquí.',
        'Desde el tejado más alto se veía la montaña. Había una luz en la cima, pequeñita y temblorosa, como alguien que espera a que vayan a buscarle.',
      ],
    },
    'montana-manta': {
      name: 'Montaña de la Manta',
      the: 'la Montaña de la Manta',
      from: 'de la Montaña de la Manta',
      caption: 'La nieve de aquí abriga en vez de enfriar.',
      quote: 'La nieve estaba calentita. Te lo juro.',
      stories: [
        'La nieve de esta montaña estaba calentita. Te lo juro. Hice un muñeco y me dio las gracias con un abrazo muy suave.',
        'Subí despacito, con muchas paradas para mirar el paisaje. Bueno, y para descansar. Sobre todo para descansar.',
        'Casi en la cima encontré unas huellas diminutas en forma de estrella. Iban hacia un jardín escondido entre las nubes. Mañana, si brillo, voy.',
      ],
    },
    'jardin-estrellas': {
      name: 'Jardín de las Estrellas Caídas',
      the: 'el Jardín de las Estrellas Caídas',
      from: 'del Jardín de las Estrellas Caídas',
      caption: 'Donde descansan las estrellas que se caen.',
      quote: 'La encontré. Y también me encontró ella.',
      stories: [
        'Por fin la encontré: una estrellita pequeña, sentada entre flores de luna. Se había caído y le daba vergüenza volver. Le dije que a mí también me pasa, y se rio.',
        'Las cartas, las barcas, el polvo dorado: era ella, dejando pistas por si alguien la buscaba. Y yo la buscaba. La encontré, y también me encontró ella.',
        'Hoy estuvimos brillando juntas en el jardín. Dice que no tiene prisa por subir al cielo, que aquí abajo se está muy bien. Le he hablado de ti.',
      ],
    },
    'observatorio-cometas': {
      name: 'Observatorio de los Cometas',
      the: 'el Observatorio de los Cometas',
      from: 'del Observatorio de los Cometas',
      caption: 'Una cúpula vieja que aún mira hacia arriba.',
      quote: 'Conté cometas hasta quedarme dormida.',
      stories: [
        'El observatorio está abandonado, pero el telescopio sigue apuntando al cielo por costumbre. Conté cometas hasta quedarme dormida.',
        'Un mochuelo astrónomo apunta las estrellas en un cuaderno. Me enseñó un hueco en una constelación: falta una, pequeñita. Dice que volverá cuando quiera.',
        'Arreglé la cúpula con un engranaje del mercadillo. Se abrió con un crujido larguísimo y entró tanta luz que parecía de día.',
      ],
    },
  },
  items: {
    piedra: {
      name: 'Piedra lisa',
      a: 'una piedra lisa',
      feminine: true,
    },
    semilla: {
      name: 'Semilla voladora',
      a: 'una semilla voladora',
      feminine: true,
    },
    trebol: {
      name: 'Trébol',
      a: 'un trébol',
      feminine: false,
    },
    seta: {
      name: 'Seta brillante',
      a: 'una seta brillante',
      feminine: true,
    },
    cristal: {
      name: 'Cristal pequeño',
      a: 'un cristal pequeño',
      feminine: false,
    },
    farolillo: {
      name: 'Farolillo',
      a: 'un farolillo',
      feminine: false,
    },
    bellota: {
      name: 'Bellota con gorrito',
      a: 'una bellota con gorrito',
      feminine: true,
    },
    pluma: {
      name: 'Pluma de búho',
      a: 'una pluma de búho',
      feminine: true,
    },
    hoja: {
      name: 'Hoja dorada',
      a: 'una hoja dorada',
      feminine: true,
    },
    concha: {
      name: 'Concha rosa',
      a: 'una concha rosa',
      feminine: true,
    },
    gota: {
      name: 'Gota de rocío',
      a: 'una gota de rocío',
      feminine: true,
    },
    llave: {
      name: 'Llave diminuta',
      a: 'una llave diminuta',
      feminine: true,
    },
    boton: {
      name: 'Botón perdido',
      a: 'un botón perdido',
      feminine: false,
    },
    galleta: {
      name: 'Galleta de avena',
      a: 'una galleta de avena',
      feminine: true,
    },
    taza: {
      name: 'Taza sin asa',
      a: 'una taza sin asa',
      feminine: true,
    },
    barquito: {
      name: 'Barquito de papel',
      a: 'un barquito de papel',
      feminine: false,
    },
    canica: {
      name: 'Canica de agua',
      a: 'una canica de agua',
      feminine: true,
    },
    campanilla: {
      name: 'Campanilla',
      a: 'una campanilla',
      feminine: true,
    },
    'flor-luna': {
      name: 'Flor de luna',
      a: 'una flor de luna',
      feminine: true,
    },
    fresa: {
      name: 'Fresa silvestre',
      a: 'una fresa silvestre',
      feminine: true,
    },
    ovillo: {
      name: 'Ovillo de lana',
      a: 'un ovillo de lana',
      feminine: false,
    },
    mapa: {
      name: 'Mapa arrugado',
      a: 'un mapa arrugado',
      feminine: false,
    },
    carta: {
      name: 'Carta sin remite',
      a: 'una carta sin remite',
      feminine: true,
    },
    reloj: {
      name: 'Reloj de bolsillo',
      a: 'un reloj de bolsillo',
      feminine: false,
    },
    engranaje: {
      name: 'Engranaje',
      a: 'un engranaje',
      feminine: false,
    },
    vela: {
      name: 'Vela de cera',
      a: 'una vela de cera',
      feminine: true,
    },
    catalejo: {
      name: 'Catalejo',
      a: 'un catalejo',
      feminine: false,
    },
    'polvo-estrella': {
      name: 'Frasco de polvo de estrellas',
      a: 'un frasco de polvo de estrellas',
      feminine: false,
    },
    'trocito-luna': {
      name: 'Trocito de luna',
      a: 'un trocito de luna',
      feminine: false,
    },
    pina: {
      name: 'Piña',
      a: 'una piña',
      feminine: true,
    },
    geoda: {
      name: 'Geoda',
      a: 'una geoda',
      feminine: true,
    },
    nenufar: {
      name: 'Nenúfar',
      a: 'un nenúfar',
      feminine: false,
    },
    bufanda: {
      name: 'Bufanda diminuta',
      a: 'una bufanda diminuta',
      feminine: true,
    },
    moneda: {
      name: 'Moneda antigua',
      a: 'una moneda antigua',
      feminine: true,
    },
    calcetin: {
      name: 'Calcetín suelto',
      a: 'un calcetín suelto',
      feminine: false,
    },
    burbuja: {
      name: 'Burbuja que no explota',
      a: 'una burbuja que no explota',
      feminine: true,
    },
  },
  friends: {
    musguito: {
      name: 'Musguito',
      a: 'Musguito',
      feminine: false,
    },
    hollin: {
      name: 'Hollín',
      a: 'Hollín',
      feminine: false,
    },
    nubecilla: {
      name: 'Nubecilla',
      a: 'Nubecilla',
      feminine: true,
    },
    chispin: {
      name: 'Chispín',
      a: 'Chispín',
      feminine: false,
    },
    topito: {
      name: 'Topito',
      a: 'Topito',
      feminine: false,
    },
    pinchito: {
      name: 'Pinchito',
      a: 'Pinchito',
      feminine: false,
    },
    ranita: {
      name: 'Ranita Do',
      a: 'Ranita Do',
      feminine: true,
    },
    caracolina: {
      name: 'Caracolina',
      a: 'Caracolina',
      feminine: true,
    },
    burbujo: {
      name: 'Burbujo',
      a: 'Burbujo',
      feminine: false,
    },
    pinzas: {
      name: 'Pinzas',
      a: 'Pinzas',
      feminine: false,
    },
    mochuelito: {
      name: 'Mochuelito',
      a: 'Mochuelito',
      feminine: false,
    },
    estrellita: {
      name: 'Estrellita',
      a: 'Estrellita',
      feminine: true,
    },
  },
} satisfies GameContent;
