import type { GameContent } from './types';

/** Français. Lampi parle au féminin. */
export default {
  chapters: {
    1: 'Ce qu’il y a derrière la maison',
    2: 'Voisins et rumeurs',
    3: 'Ce que garde l’eau',
    4: 'Vers les étoiles',
  },
  places: {
    'bosque-musgo': {
      name: 'Bois de Mousse',
      the: 'le Bois de Mousse',
      from: 'du Bois de Mousse',
      caption: 'Ici, tout est tout doux. Même le silence.',
      quote: 'Je me suis endormie sans le vouloir.',
      stories: [
        'La mousse était si douce que je me suis endormie sans le vouloir. À mon réveil, quelqu’un m’avait couverte d’une feuille.',
        'Les arbres d’ici parlent tout bas, presque en chuchotant. Je crois que l’un d’eux m’a dit « bienvenue », mais c’était peut-être le vent.',
        'J’ai trouvé un petit chemin de poussière dorée entre les racines. Je l’ai suivi un moment, mais il disparaissait juste là où il commençait à faire nuit. Bizarre, non ?',
      ],
    },
    'pradera-suave': {
      name: 'Prairie Douce',
      the: 'la Prairie Douce',
      from: 'de la Prairie Douce',
      caption: 'De l’herbe jusqu’aux oreilles et zéro hâte.',
      quote: 'Je t’ai gardé un trèfle.',
      stories: [
        'J’ai passé l’après-midi à chercher un trèfle à quatre feuilles. J’en ai trouvé un à trois feuilles très sympathique, et ça m’a suffi. Je te l’ai gardé.',
        'J’ai roulé six fois au bas de la pente. À la septième, j’ai eu un peu le tournis, alors je me suis allongée pour regarder passer les nuages.',
        'Il y avait des fraises cachées sous les feuilles, comme si elles jouaient à cache-cache. J’ai gagné. Bon, et j’en ai mangé quelques-unes.',
      ],
    },
    'dientes-de-leon': {
      name: 'Colline des Pissenlits',
      the: 'la Colline des Pissenlits',
      from: 'de la Colline des Pissenlits',
      caption: 'Chaque souffle est un tout petit vœu.',
      quote: 'Je me suis fait une amie d’un souffle.',
      stories: [
        'J’ai soufflé sur un pissenlit et ses graines sont parties en file, très sérieuses. L’une d’elles est restée avec moi. Je me suis fait une amie d’un souffle.',
        'Du haut de la colline, on voit notre maison. Je t’ai fait coucou avec ma lumière, au cas où tu regardais par la fenêtre.',
        'La nuit, au sommet, j’ai vu une petite lumière traverser le ciel et tomber derrière la forêt. Sans un bruit. J’aurais bien voulu savoir où elle est allée.',
      ],
    },
    'jardin-setas': {
      name: 'Jardin des Champignons',
      the: 'le Jardin des Champignons',
      from: 'du Jardin des Champignons',
      caption: 'Des champignons grands comme des parapluies. Et comme des dés à coudre.',
      quote: 'Un champignon m’a fait un clin d’œil. Je crois.',
      stories: [
        'Un champignon m’a fait un clin d’œil. Je crois. Je lui en ai fait un aussi, par politesse, et il est devenu encore plus rouge.',
        'Il s’est mis à bruiner, alors je me suis abritée sous le plus grand champignon. Trois scarabées y jouaient déjà aux cartes. Ils m’ont laissée regarder.',
        'Les champignons d’ici brillent un peu la nuit, comme moi. On a brillé ensemble un moment et c’était très agréable.',
      ],
    },
    'lago-lunas': {
      name: 'Lac des Lunes',
      the: 'le Lac des Lunes',
      from: 'du Lac des Lunes',
      caption: 'Une lune en haut, une autre en bas. Et moi au milieu.',
      quote: 'Il y avait deux lunes et aucune n’était en fromage.',
      stories: [
        'Il y avait deux lunes et aucune n’était en fromage. J’ai vérifié. Celle du bas se défaisait en vaguelettes chaque fois que je la touchais.',
        'J’ai fait ricocher une pierre plate sur l’eau : une, deux, trois fois. À la quatrième, elle a coulé, mais avec beaucoup de dignité.',
        'Ce soir, le lac reflétait trois lunes, et il n’y en avait que deux dans le ciel. Je suis restée immobile à regarder la troisième jusqu’à ce qu’elle s’éteigne.',
      ],
    },
    'madriguera-vecino': {
      name: 'Terrier du Voisin',
      the: 'le Terrier du Voisin',
      from: 'du Terrier du Voisin',
      caption: 'Ça sent le pain grillé et la bonne terre.',
      quote: 'Il avait des biscuits. Je ne t’en dis pas plus.',
      stories: [
        'Le voisin est une taupe à lunettes qui voit très mal mais qui cuisine à merveille. Il avait des biscuits. Je ne t’en dis pas plus.',
        'Il m’a montré sa collection de boutons : cent douze, et aucun ne va par paire. Il dit que les autres finiront bien par apparaître.',
        'Pendant le goûter, il m’a raconté qu’il y a quelques nuits il a entendu quelque chose tomber dans la forêt, « comme une clochette qui trébuche ». Puis il a changé de sujet, mais moi, j’y ai repensé.',
      ],
    },
    'nube-baja': {
      name: 'Nuage Bas',
      the: 'le Nuage Bas',
      from: 'du Nuage Bas',
      caption: 'Un nuage qui a décidé de vivre par terre.',
      quote: 'Il était tout doux et un peu mouillé.',
      stories: [
        'Le nuage était tout doux et un peu mouillé. Je m’y suis enfoncée jusqu’aux oreilles et j’en suis ressortie avec les cheveux, enfin, la lumière, toute frisée.',
        'Dans le nuage, on ne voit rien, alors j’ai joué à deviner des formes les yeux fermés. J’ai toujours gagné, puisque personne ne pouvait me contredire.',
        'Le nuage m’a dit qu’il ne veut pas monter au ciel parce qu’il y a trop de vent là-haut. Je lui ai dit qu’en bas aussi, on est très bien. Je crois que ça lui a plu.',
      ],
    },
    'puente-raices': {
      name: 'Pont de Racines',
      the: 'le Pont de Racines',
      from: 'du Pont de Racines',
      caption: 'Un pont qui a poussé tout seul, sans se presser.',
      quote: 'J’ai traversé sur la pointe des pieds pour ne pas le réveiller.',
      stories: [
        'Le pont est fait de racines qui se sont donné la main il y a très, très longtemps. J’ai traversé sur la pointe des pieds pour ne pas le réveiller.',
        'Au milieu du pont, un hérisson était coincé entre deux racines. Je l’ai poussé doucement et il est sorti en roulant, très digne, comme si de rien n’était.',
        'Accrochée à une racine, j’ai trouvé une lettre sans expéditeur. Elle disait seulement : « Pour qui trouvera le chemin doré ». Et si c’était pour moi ?',
      ],
    },
    'cuevas-cristal': {
      name: 'Grottes de Cristal',
      the: 'les Grottes de Cristal',
      from: 'des Grottes de Cristal',
      caption: 'Chaque fois que je brille, la grotte brille avec moi.',
      quote: 'Ma lumière rebondissait partout.',
      stories: [
        'Dans la grotte, ma lumière rebondissait partout. Un instant, j’ai cru qu’on était cent Lampi, et ça m’a un peu intimidée.',
        'De petites boules de suie vivent dans les coins sombres. Au début, elles se sont cachées, mais quand je me suis assise sans bouger, elles sont venues se réchauffer contre moi.',
        'Sur la paroi la plus profonde, il y a un très vieux dessin : une étoile avec un petit visage, en train de tomber. Quelqu’un l’a peint il y a longtemps. Ou peut-être pas si longtemps.',
      ],
    },
    'faro-dormido': {
      name: 'Phare Endormi',
      the: 'le Phare Endormi',
      from: 'du Phare Endormi',
      caption: 'Un phare qui s’est éteint pour faire la sieste.',
      quote: 'Je lui ai prêté ma lumière un petit moment.',
      stories: [
        'Le phare dort depuis des années et ronfle un peu quand le vent souffle. Je lui ai prêté ma lumière un petit moment et il a clignoté, comme s’il faisait un joli rêve.',
        'J’ai monté les cent quarante marches. Tout en haut vit une petite chouette qui s’occupe de tout pendant que le phare dort. Elle était épuisée, alors je lui ai tenu compagnie.',
        'Avec la longue-vue du phare, on voit très loin. J’ai vu une île avec une énorme horloge arrêtée, et un bateau en papier qui voguait vers elle.',
      ],
    },
    'charca-ranas': {
      name: 'Mare des Grenouilles Chanteuses',
      the: 'la Mare des Grenouilles Chanteuses',
      from: 'de la Mare des Grenouilles Chanteuses',
      caption: 'Ici, la chorale répète tous les soirs.',
      quote: 'Elles m’ont laissée chanter le do. Seulement le do.',
      stories: [
        'Les grenouilles ont une chorale et elles m’ont laissée chanter le do. Seulement le do. Je l’ai chanté avec beaucoup d’émotion.',
        'Une toute petite grenouille se trompait toujours de note et les autres la regardaient de travers. Pour moi, c’était elle qui chantait le mieux.',
        'Les grenouilles disent que l’eau se souvient de tout ce qu’elle a reflété. Je leur ai parlé de la troisième lune et elles se sont tues toutes les quarante en même temps.',
      ],
    },
    'cascada-timida': {
      name: 'Cascade Timide',
      the: 'la Cascade Timide',
      from: 'de la Cascade Timide',
      caption: 'Elle ne tombe que quand elle croit que personne ne regarde.',
      quote: 'Je me suis retournée et elle s’est mise à tomber.',
      stories: [
        'La cascade ne tombe que quand personne ne la regarde. Je me suis retournée et elle s’est mise à tomber, toute contente. Je l’ai vue du coin de l’œil, mais je n’ai rien dit.',
        'Derrière l’eau, il y a une petite grotte où des escargots collectionnent les gouttes. Ils m’en ont offert une. J’ai trouvé ça adorable.',
        'Au pied de la cascade, entre les pierres, brillait un peu de poussière dorée. La même que dans la forêt. Le chemin continue, et il va vers la mer.',
      ],
    },
    'playa-conchas': {
      name: 'Plage des Coquillages',
      the: 'la Plage des Coquillages',
      from: 'de la Plage des Coquillages',
      caption: 'Du sable tiède et des vagues qui ne sont pas pressées.',
      quote: 'Une vague m’a apporté un coquillage et s’en est allée.',
      stories: [
        'Une vague m’a apporté un coquillage et s’est sauvée en courant, comme si elle était gênée. Elle est vite revenue voir s’il m’avait plu.',
        'Un crabe m’a défiée à la course en marchant de côté. J’ai perdu, évidemment, parce que je flotte. Il a dit que c’était de la triche, mais on a beaucoup ri.',
        'J’ai fait un château de sable avec une tour et tout. La marée l’a emporté très délicatement, presque en demandant la permission.',
      ],
    },
    'muelle-barcas': {
      name: 'Quai des Bateaux en Papier',
      the: 'le Quai des Bateaux en Papier',
      from: 'du Quai des Bateaux en Papier',
      caption: 'Chaque bateau emporte un message.',
      quote: 'J’ai plié un bateau et j’y ai écrit ton prénom.',
      stories: [
        'Ici, les gens plient des bateaux en papier et les laissent partir avec un message. J’en ai plié un et j’y ai écrit ton prénom. On verra bien où il arrive.',
        'Un petit poisson sortait la tête chaque fois qu’un bateau passait, pour lire les messages. Très curieux, mais très gentil.',
        'Un bateau est revenu au quai avec la même écriture que la lettre du pont : « Presque. Regarde en haut ». Ça m’a donné un joli frisson.',
      ],
    },
    'isla-reloj': {
      name: 'Île de l’Horloge Arrêtée',
      the: 'l’Île de l’Horloge Arrêtée',
      from: 'de l’Île de l’Horloge Arrêtée',
      caption: 'Ici, il est toujours onze heures et quart.',
      quote: 'Ici, personne n’est jamais en retard.',
      stories: [
        'Sur cette île, il est toujours onze heures et quart, alors personne n’est jamais en retard. J’ai pris mon après-midi avec beaucoup de calme.',
        'Les crabes de l’île remontent l’horloge chacun leur tour, même si elle ne bouge pas. Ils disent que c’est au cas où, et je trouve ça très sage.',
        'L’horloge s’est arrêtée la nuit même où la petite lumière est tombée. Je lui ai donné une pichenette et les aiguilles ont tremblé, comme si elles voulaient montrer quelque chose dans le ciel.',
      ],
    },
    'mercadillo-buhos': {
      name: 'Marché des Hiboux',
      the: 'le Marché des Hiboux',
      from: 'du Marché des Hiboux',
      caption: 'Ouvre à minuit. On paie avec des histoires.',
      quote: 'J’ai payé une carte avec une de tes histoires.',
      stories: [
        'Dans ce marché, rien ne se paie avec de l’argent, seulement avec des histoires. J’ai payé une carte avec une de tes histoires. J’espère que ça ne te dérange pas.',
        'Un hibou très sérieux vend des engrenages et ne veut pas dire à quoi ils servent. Il m’a fait un clin d’œil, alors ça doit être important.',
        'La carte que j’ai achetée a une croix dessinée en haut de la montagne, à côté d’une petite étoile. On dirait qu’on y est presque.',
      ],
    },
    'tejados-aldea': {
      name: 'Toits du Village Endormi',
      the: 'les Toits du Village Endormi',
      from: 'des Toits du Village Endormi',
      caption: 'Des cheminées bien chaudes et des chats philosophes.',
      quote: 'Je me suis promenée de cheminée en cheminée.',
      stories: [
        'Je me suis promenée de cheminée en cheminée, en me réchauffant le ventre. Un chat m’a expliqué que la nuit, c’est fait pour réfléchir. Puis il s’est endormi.',
        'Sur une corde à linge, il y avait des chaussettes de toutes les couleurs et aucune paire. J’ai pensé au voisin et à ses boutons. Il se passe quelque chose avec les paires, par ici.',
        'Du toit le plus haut, on voyait la montagne. Il y avait une lumière au sommet, toute petite et tremblante, comme quelqu’un qui attend qu’on vienne le chercher.',
      ],
    },
    'montana-manta': {
      name: 'Montagne Couverture',
      the: 'la Montagne Couverture',
      from: 'de la Montagne Couverture',
      caption: 'Ici, la neige réchauffe au lieu de refroidir.',
      quote: 'La neige était toute chaude. Je te le jure.',
      stories: [
        'La neige de cette montagne était toute chaude. Je te le jure. J’ai fait un bonhomme de neige et il m’a remerciée avec un câlin très doux.',
        'J’ai grimpé tout doucement, avec plein de pauses pour admirer le paysage. Bon, et pour me reposer. Surtout pour me reposer.',
        'Presque au sommet, j’ai trouvé de minuscules empreintes en forme d’étoile. Elles menaient à un jardin caché dans les nuages. Demain, si je brille, j’y vais.',
      ],
    },
    'jardin-estrellas': {
      name: 'Jardin des Étoiles Tombées',
      the: 'le Jardin des Étoiles Tombées',
      from: 'du Jardin des Étoiles Tombées',
      caption: 'Là où se reposent les étoiles qui tombent.',
      quote: 'Je l’ai trouvée. Et elle m’a trouvée aussi.',
      stories: [
        'Enfin, je l’ai trouvée : une toute petite étoile, assise parmi les fleurs de lune. Elle était tombée et n’osait pas remonter. Je lui ai dit que ça m’arrive aussi, et elle a ri.',
        'Les lettres, les bateaux, la poussière dorée : c’était elle, qui laissait des indices au cas où quelqu’un la chercherait. Et moi, je la cherchais. Je l’ai trouvée, et elle m’a trouvée aussi.',
        'Aujourd’hui, on a brillé ensemble dans le jardin. Elle dit qu’elle n’est pas pressée de remonter au ciel, qu’on est très bien ici. Je lui ai parlé de toi.',
      ],
    },
    'observatorio-cometas': {
      name: 'Observatoire des Comètes',
      the: 'l’Observatoire des Comètes',
      from: 'de l’Observatoire des Comètes',
      caption: 'Une vieille coupole qui regarde encore vers le haut.',
      quote: 'J’ai compté les comètes jusqu’à m’endormir.',
      stories: [
        'L’observatoire est abandonné, mais le télescope pointe toujours vers le ciel, par habitude. J’ai compté les comètes jusqu’à m’endormir.',
        'Une petite chouette astronome note les étoiles dans un carnet. Elle m’a montré un trou dans une constellation : il en manque une, toute petite. Elle dit qu’elle reviendra quand elle voudra.',
        'J’ai réparé la coupole avec un engrenage du marché. Elle s’est ouverte avec un très long grincement et il est entré tant de lumière qu’on aurait dit le jour.',
      ],
    },
  },
  items: {
    piedra: { name: 'Pierre lisse', a: 'une pierre lisse', feminine: true },
    semilla: {
      name: 'Graine volante',
      a: 'une graine volante',
      feminine: true,
    },
    trebol: { name: 'Trèfle', a: 'un trèfle', feminine: false },
    seta: {
      name: 'Champignon lumineux',
      a: 'un champignon lumineux',
      feminine: false,
    },
    cristal: { name: 'Petit cristal', a: 'un petit cristal', feminine: false },
    farolillo: { name: 'Lampion', a: 'un lampion', feminine: false },
    bellota: {
      name: 'Gland à chapeau',
      a: 'un gland à chapeau',
      feminine: false,
    },
    pluma: { name: 'Plume de hibou', a: 'une plume de hibou', feminine: true },
    hoja: { name: 'Feuille dorée', a: 'une feuille dorée', feminine: true },
    concha: {
      name: 'Coquillage rose',
      a: 'un coquillage rose',
      feminine: false,
    },
    gota: { name: 'Goutte de rosée', a: 'une goutte de rosée', feminine: true },
    llave: { name: 'Clé minuscule', a: 'une clé minuscule', feminine: true },
    boton: { name: 'Bouton perdu', a: 'un bouton perdu', feminine: false },
    galleta: {
      name: 'Biscuit à l’avoine',
      a: 'un biscuit à l’avoine',
      feminine: false,
    },
    taza: { name: 'Tasse sans anse', a: 'une tasse sans anse', feminine: true },
    barquito: {
      name: 'Bateau en papier',
      a: 'un bateau en papier',
      feminine: false,
    },
    canica: { name: 'Bille d’eau', a: 'une bille d’eau', feminine: true },
    campanilla: { name: 'Clochette', a: 'une clochette', feminine: true },
    'flor-luna': {
      name: 'Fleur de lune',
      a: 'une fleur de lune',
      feminine: true,
    },
    fresa: {
      name: 'Fraise des bois',
      a: 'une fraise des bois',
      feminine: true,
    },
    ovillo: {
      name: 'Pelote de laine',
      a: 'une pelote de laine',
      feminine: true,
    },
    mapa: { name: 'Carte froissée', a: 'une carte froissée', feminine: true },
    carta: {
      name: 'Lettre sans expéditeur',
      a: 'une lettre sans expéditeur',
      feminine: true,
    },
    reloj: {
      name: 'Montre à gousset',
      a: 'une montre à gousset',
      feminine: true,
    },
    engranaje: { name: 'Engrenage', a: 'un engrenage', feminine: false },
    vela: { name: 'Bougie en cire', a: 'une bougie en cire', feminine: true },
    catalejo: { name: 'Longue-vue', a: 'une longue-vue', feminine: true },
    'polvo-estrella': {
      name: 'Poussière d’étoiles',
      a: 'un flacon de poussière d’étoiles',
      feminine: true,
    },
    'trocito-luna': {
      name: 'Petit bout de lune',
      a: 'un petit bout de lune',
      feminine: false,
    },
    pina: { name: 'Pomme de pin', a: 'une pomme de pin', feminine: true },
    geoda: { name: 'Géode', a: 'une géode', feminine: true },
    nenufar: { name: 'Nénuphar', a: 'un nénuphar', feminine: false },
    bufanda: {
      name: 'Écharpe minuscule',
      a: 'une écharpe minuscule',
      feminine: true,
    },
    moneda: { name: 'Pièce ancienne', a: 'une pièce ancienne', feminine: true },
    calcetin: {
      name: 'Chaussette orpheline',
      a: 'une chaussette orpheline',
      feminine: true,
    },
    burbuja: {
      name: 'Bulle qui n’éclate pas',
      a: 'une bulle qui n’éclate pas',
      feminine: true,
    },
  },
  friends: {
    musguito: { name: 'Moussinet', a: 'Moussinet', feminine: false },
    hollin: { name: 'Suiton', a: 'Suiton', feminine: false },
    nubecilla: { name: 'Nuageotte', a: 'Nuageotte', feminine: true },
    chispin: { name: 'Étincelou', a: 'Étincelou', feminine: false },
    topito: { name: 'Taupinou', a: 'Taupinou', feminine: false },
    pinchito: { name: 'Piquant', a: 'Piquant', feminine: false },
    ranita: { name: 'Rainette Do', a: 'Rainette Do', feminine: true },
    caracolina: { name: 'Coquilline', a: 'Coquilline', feminine: true },
    burbujo: { name: 'Bulloche', a: 'Bulloche', feminine: false },
    pinzas: { name: 'Pinceur', a: 'Pinceur', feminine: false },
    mochuelito: { name: 'Chouettou', a: 'Chouettou', feminine: false },
    estrellita: { name: 'Étoilette', a: 'Étoilette', feminine: true },
  },
} satisfies GameContent;
