import type { Destination } from '@/game/types';

/**
 * Los 20 destinos del MVP, en 4 capítulos de 5 lugares.
 * El orden del array es el orden de la historia: `pickDestination` propone
 * primero los que Lumi aún no conoce, en este orden.
 *
 * Hilo largo: una estrellita se cayó del cielo hace poco. Lumi encuentra
 * pistas sueltas (polvo dorado, una carta sin remite, un reflejo sin dueña)
 * hasta dar con ella en el Jardín de las Estrellas Caídas.
 */
export const DESTINATIONS: Destination[] = [
  // ── Capítulo 1 ─────────────────────────────────────────────
  {
    id: 'bosque-musgo',
    name: 'Bosque de Musgo',
    article: 'el',
    art: 'linear-gradient(170deg, #8FD1A6, #3E6A6A 55%, #1D2446)',
    chapter: 1,
    chapterTitle: 'Lo que hay detrás de casa',
    caption: 'Aquí todo es blandito. Hasta el silencio.',
    quote: 'Me eché una siesta sin querer.',
    stories: [
      'El musgo estaba tan blandito que me eché una siesta sin querer. Cuando me desperté, alguien me había tapado con una hoja.',
      'Los árboles de aquí hablan muy bajito, casi en susurros. Creo que uno me dijo «bienvenida», pero igual era el viento.',
      'Encontré un caminito de polvo dorado entre las raíces. Lo seguí un rato, pero se perdía justo donde empezaba a oscurecer. Qué raro, ¿no?',
    ],
    plus: false,
    unlockAfterBrightDays: 0,
    lootItems: ['seta', 'trebol', 'bellota', 'pina', 'hoja'],
    lootFriends: ['musguito'],
  },
  {
    id: 'pradera-suave',
    name: 'Pradera Suave',
    article: 'la',
    art: 'linear-gradient(170deg, #8FD1A6, #3E6A6A 60%, #1D2446)',
    chapter: 1,
    chapterTitle: 'Lo que hay detrás de casa',
    caption: 'Hierba hasta las orejas y cero prisas.',
    quote: 'Te guardé un trébol.',
    stories: [
      'Me pasé la tarde buscando un trébol de cuatro hojas. Encontré uno de tres muy simpático y me pareció suficiente. Te lo he guardado.',
      'Rodé cuesta abajo seis veces. La séptima me mareé un poquito, así que me tumbé a mirar cómo pasaban las nubes.',
      'Había fresas escondidas debajo de las hojas, como si jugaran al escondite. Gané yo. Bueno, y alguna me comí.',
    ],
    plus: false,
    unlockAfterBrightDays: 0,
    lootItems: ['trebol', 'fresa', 'semilla', 'calcetin'],
    lootFriends: ['musguito'],
  },
  {
    id: 'dientes-de-leon',
    name: 'Colina de los Dientes de León',
    article: 'la',
    art: 'linear-gradient(170deg, #FFE3A3, #FFB4A2 60%, #8C7BD8)',
    chapter: 1,
    chapterTitle: 'Lo que hay detrás de casa',
    caption: 'Cada soplido es un deseo pequeñito.',
    quote: 'Me hice amiga de un soplido.',
    stories: [
      'Soplé un diente de león y sus semillas se fueron volando en fila, muy formales. Una se quedó conmigo. Me hice amiga de un soplido.',
      'Desde lo alto de la colina se ve nuestra casa. Te saludé con la luz, por si acaso mirabas por la ventana.',
      'Por la noche, en la cima, vi una lucecita cruzar el cielo y caer detrás del bosque. No hizo ruido. Me quedé con ganas de saber adónde fue.',
    ],
    plus: false,
    unlockAfterBrightDays: 1,
    lootItems: ['semilla', 'pluma', 'burbuja', 'boton'],
    lootFriends: ['chispin'],
  },
  {
    id: 'jardin-setas',
    name: 'Jardín de Setas',
    article: 'el',
    art: 'linear-gradient(170deg, #FFB4A2, #8C7BD8 60%, #2A2560)',
    chapter: 1,
    chapterTitle: 'Lo que hay detrás de casa',
    caption: 'Setas del tamaño de paraguas. Y de dedales.',
    quote: 'Una seta me guiñó un ojo. Creo.',
    stories: [
      'Una seta me guiñó un ojo. Creo. Le guiñé yo también, por educación, y se puso más colorada todavía.',
      'Empezó a chispear y me refugié debajo de la seta más grande. Allí ya había tres escarabajos jugando a las cartas. Me dejaron mirar.',
      'Las setas de aquí brillan un poco por la noche, como yo. Estuvimos un rato brillando juntas y fue muy agradable.',
    ],
    plus: false,
    unlockAfterBrightDays: 2,
    lootItems: ['seta', 'gota', 'campanilla', 'canica'],
    lootFriends: ['chispin'],
  },
  {
    id: 'lago-lunas',
    name: 'Lago de las Lunas',
    article: 'el',
    art: 'linear-gradient(170deg, #C9BFF2, #5F82C8 55%, #2A2560)',
    chapter: 1,
    chapterTitle: 'Lo que hay detrás de casa',
    caption: 'Una luna arriba, otra abajo. Y yo en medio.',
    quote: 'Había dos lunas y ninguna era de queso.',
    stories: [
      'Había dos lunas y ninguna era de queso. Lo comprobé. La de abajo se deshacía en ondas cada vez que la tocaba.',
      'Hice saltar una piedra lisa sobre el agua: una, dos, tres veces. A la cuarta se hundió, pero con mucha dignidad.',
      'Esta noche el lago reflejaba tres lunas, y en el cielo solo había dos. Me quedé muy quieta mirando la tercera hasta que se apagó.',
    ],
    plus: false,
    unlockAfterBrightDays: 3,
    lootItems: ['piedra', 'trocito-luna', 'nenufar', 'gota'],
    lootFriends: ['burbujo'],
  },

  // ── Capítulo 2 ─────────────────────────────────────────────
  {
    id: 'madriguera-vecino',
    name: 'Madriguera del Vecino',
    article: 'la',
    art: 'linear-gradient(170deg, #FFC96B, #6B4A3E 70%)',
    chapter: 2,
    chapterTitle: 'Vecinos y rumores',
    caption: 'Huele a pan tostado y a tierra buena.',
    quote: 'Tenía galletas. No te digo más.',
    stories: [
      'El vecino es un topo con gafas que ve fatal pero cocina de maravilla. Tenía galletas. No te digo más.',
      'Me enseñó su colección de botones: ciento doce, y ninguno hace pareja. Dice que algún día aparecerán los otros.',
      'Mientras merendábamos me contó que hace unas noches oyó algo caer en el bosque, «como una campanilla que se tropieza». Luego cambió de tema, pero yo me quedé pensando.',
    ],
    plus: false,
    unlockAfterBrightDays: 4,
    lootItems: ['galleta', 'taza', 'ovillo', 'boton', 'llave'],
    lootFriends: ['topito'],
  },
  {
    id: 'nube-baja',
    name: 'Nube Baja',
    article: 'la',
    art: 'linear-gradient(170deg, #E6E0FB, #8C7BD8 50%, #1B1840)',
    chapter: 2,
    chapterTitle: 'Vecinos y rumores',
    caption: 'Una nube que se quedó a vivir en el suelo.',
    quote: 'Estaba blandita y un poco mojada.',
    stories: [
      'La nube estaba blandita y un poco mojada. Me hundí hasta las orejas y salí con el pelo, bueno, la luz, toda rizada.',
      'Dentro de la nube no se ve nada, así que jugué a adivinar formas con los ojos cerrados. Gané siempre, porque nadie podía llevarme la contraria.',
      'La nube me contó que no quiere subir al cielo porque allí arriba hay mucho viento. Yo le dije que abajo también se está muy bien. Creo que le gustó.',
    ],
    plus: false,
    unlockAfterBrightDays: 5,
    lootItems: ['gota', 'burbuja', 'pluma', 'bufanda'],
    lootFriends: ['nubecilla'],
  },
  {
    id: 'puente-raices',
    name: 'Puente de Raíces',
    article: 'el',
    art: 'linear-gradient(165deg, #8FD1A6, #8C7BD8 55%, #13112E)',
    chapter: 2,
    chapterTitle: 'Vecinos y rumores',
    caption: 'Un puente que creció solo, sin prisa.',
    quote: 'Crucé de puntillas para no despertarlo.',
    stories: [
      'El puente está hecho de raíces que se dieron la mano hace muchísimos años. Crucé de puntillas para no despertarlo.',
      'A mitad del puente había un erizo atascado entre dos raíces. Lo empujé con cuidado y salió rodando, muy digno, como si no hubiera pasado nada.',
      'Enganchada en una raíz encontré una carta sin remite. Solo ponía: «Para quien encuentre el camino dorado». ¿Será para mí?',
    ],
    plus: false,
    unlockAfterBrightDays: 6,
    lootItems: ['bellota', 'hoja', 'carta', 'calcetin'],
    lootFriends: ['pinchito'],
  },
  {
    id: 'cuevas-cristal',
    name: 'Cuevas de Cristal',
    article: 'las',
    art: 'linear-gradient(160deg, #9FE3F0, #6A5FC0 60%, #1B1840)',
    chapter: 2,
    chapterTitle: 'Vecinos y rumores',
    caption: 'Cada vez que brillo, la cueva brilla conmigo.',
    quote: 'Mi luz rebotaba por todas partes.',
    stories: [
      'Dentro de la cueva mi luz rebotaba por todas partes. Por un momento pensé que éramos cien Lumis, y me dio un poco de vergüenza.',
      'Unos bichitos de hollín viven en los rincones oscuros. Al principio se escondieron, pero cuando me senté quieta vinieron a calentarse conmigo.',
      'En la pared más honda hay un dibujo muy antiguo: una estrella con carita, cayendo. Alguien lo pintó hace mucho. O a lo mejor no hace tanto.',
    ],
    plus: false,
    unlockAfterBrightDays: 7,
    lootItems: ['cristal', 'geoda', 'piedra', 'vela', 'moneda'],
    lootFriends: ['hollin'],
  },
  {
    id: 'faro-dormido',
    name: 'Faro Dormido',
    article: 'el',
    art: 'linear-gradient(160deg, #FFC96B, #B06A7A 60%, #2A2560)',
    chapter: 2,
    chapterTitle: 'Vecinos y rumores',
    caption: 'Un faro que se apagó para echarse la siesta.',
    quote: 'Le presté mi luz un ratito.',
    stories: [
      'El faro lleva años dormido y ronca un poco cuando sopla el viento. Le presté mi luz un ratito y parpadeó, como si soñara algo bonito.',
      'Subí los ciento cuarenta escalones. Arriba vive un mochuelo que se encarga de todo mientras el faro duerme. Estaba agotado y le hice compañía.',
      'Con el catalejo del faro se ve muy lejos. Vi una isla con un reloj enorme, parado, y un barco de papel navegando hacia ella.',
    ],
    plus: true,
    unlockAfterBrightDays: 4,
    lootItems: ['farolillo', 'vela', 'catalejo', 'concha', 'llave'],
    lootFriends: ['mochuelito'],
  },

  // ── Capítulo 3 ─────────────────────────────────────────────
  {
    id: 'charca-ranas',
    name: 'Charca de las Ranas Cantoras',
    article: 'la',
    art: 'linear-gradient(165deg, #9FE3F0, #8FD1A6 45%, #2A2560)',
    chapter: 3,
    chapterTitle: 'Lo que guarda el agua',
    caption: 'Aquí se ensaya el coro todas las noches.',
    quote: 'Me dejaron cantar el do. Solo el do.',
    stories: [
      'Las ranas tienen un coro y me dejaron cantar el do. Solo el do. Lo hice con mucho sentimiento.',
      'Una rana muy pequeña se equivocaba siempre de nota y las demás la miraban raro. A mí me pareció la que mejor cantaba.',
      'Dicen las ranas que el agua recuerda todo lo que ha reflejado. Les pregunté por la tercera luna y se callaron las cuarenta a la vez.',
    ],
    plus: false,
    unlockAfterBrightDays: 8,
    lootItems: ['nenufar', 'gota', 'canica', 'flor-luna'],
    lootFriends: ['ranita'],
  },
  {
    id: 'cascada-timida',
    name: 'Cascada Tímida',
    article: 'la',
    art: 'linear-gradient(170deg, #E6E0FB, #9FE3F0 45%, #2A2560)',
    chapter: 3,
    chapterTitle: 'Lo que guarda el agua',
    caption: 'Solo cae cuando cree que nadie la mira.',
    quote: 'Me di la vuelta y se puso a caer.',
    stories: [
      'La cascada solo cae cuando nadie la mira. Me di la vuelta y se puso a caer, muy contenta. La pillé de reojo, pero no le dije nada.',
      'Detrás del agua hay una cuevecita con caracoles que coleccionan gotas. Me regalaron una. Me pareció un gesto precioso.',
      'Al pie de la cascada, entre las piedras, brillaba un poquito de polvo dorado. El mismo del bosque. El camino sigue, y va hacia el mar.',
    ],
    plus: false,
    unlockAfterBrightDays: 9,
    lootItems: ['piedra', 'flor-luna', 'burbuja', 'geoda'],
    lootFriends: ['caracolina'],
  },
  {
    id: 'playa-conchas',
    name: 'Playa de las Conchas',
    article: 'la',
    art: 'linear-gradient(165deg, #FFE3A3, #FFB4A2 50%, #2A2560)',
    chapter: 3,
    chapterTitle: 'Lo que guarda el agua',
    caption: 'Arena tibia y olas que no tienen prisa.',
    quote: 'Una ola me trajo una concha y se fue.',
    stories: [
      'Una ola me trajo una concha y se fue corriendo, como si le diera vergüenza. Volvió enseguida a ver si me había gustado.',
      'Un cangrejo me retó a correr de lado. Perdí, claro, porque yo floto. Me dijo que eso era trampa, pero nos reímos mucho.',
      'Hice un castillo de arena con torre y todo. La marea se lo llevó con mucha delicadeza, casi pidiendo permiso.',
    ],
    plus: false,
    unlockAfterBrightDays: 11,
    lootItems: ['concha', 'moneda', 'barquito', 'canica'],
    lootFriends: ['caracolina', 'pinzas'],
  },
  {
    id: 'muelle-barcas',
    name: 'Muelle de las Barcas de Papel',
    article: 'el',
    art: 'linear-gradient(170deg, #E6E0FB, #5F82C8 55%, #13112E)',
    chapter: 3,
    chapterTitle: 'Lo que guarda el agua',
    caption: 'Cada barca lleva un mensaje dentro.',
    quote: 'Doblé una barca y le puse tu nombre.',
    stories: [
      'Aquí la gente dobla barcas de papel y las suelta con un mensaje. Doblé una y le puse tu nombre. Ya verás tú adónde llega.',
      'Un pececito asomaba la cabeza cada vez que pasaba una barca, para leer los mensajes. Es muy cotilla, pero muy simpático.',
      'Una barca volvió al muelle con la misma letra que la carta del puente: «Ya casi. Mira hacia arriba». Me dio un escalofrío bonito.',
    ],
    plus: false,
    unlockAfterBrightDays: 12,
    lootItems: ['barquito', 'carta', 'bufanda', 'mapa'],
    lootFriends: ['burbujo'],
  },
  {
    id: 'isla-reloj',
    name: 'Isla del Reloj Parado',
    article: 'la',
    art: 'linear-gradient(160deg, #C9BFF2, #FFC96B 55%, #2A2560)',
    chapter: 3,
    chapterTitle: 'Lo que guarda el agua',
    caption: 'Aquí siempre son las once y cuarto.',
    quote: 'Aquí nadie llega tarde a nada.',
    stories: [
      'En esta isla siempre son las once y cuarto, así que aquí nadie llega tarde a nada. Me tomé la tarde con muchísima calma.',
      'Los cangrejos de la isla dan cuerda al reloj por turnos, aunque no se mueva. Dicen que es por si acaso, y me parece muy sensato.',
      'El reloj se paró la misma noche en que cayó la lucecita. Le di un toquecito y las agujas temblaron, como si quisieran señalar algo del cielo.',
    ],
    plus: true,
    unlockAfterBrightDays: 10,
    lootItems: ['reloj', 'engranaje', 'llave', 'mapa'],
    lootFriends: ['pinzas'],
  },

  // ── Capítulo 4 ─────────────────────────────────────────────
  {
    id: 'mercadillo-buhos',
    name: 'Mercadillo de los Búhos',
    article: 'el',
    art: 'linear-gradient(165deg, #FFC96B, #8C7BD8 55%, #1B1840)',
    chapter: 4,
    chapterTitle: 'Hacia las estrellas',
    caption: 'Abre a medianoche. Se paga con cuentos.',
    quote: 'Pagué un mapa con un cuento tuyo.',
    stories: [
      'En este mercadillo nada se paga con dinero, solo con cuentos. Pagué un mapa con un cuento tuyo. Espero que no te importe.',
      'Un búho muy serio vende engranajes sueltos y no quiere decir para qué sirven. Me guiñó un ojo, así que debe de ser algo importante.',
      'El mapa que compré tiene una equis dibujada en lo alto de la montaña, al lado de una estrellita. Tiene pinta de que ya queda poco.',
    ],
    plus: false,
    unlockAfterBrightDays: 13,
    lootItems: ['mapa', 'engranaje', 'moneda', 'catalejo', 'pluma'],
    lootFriends: ['mochuelito', 'pinchito'],
  },
  {
    id: 'tejados-aldea',
    name: 'Tejados de la Aldea Dormida',
    article: 'los',
    art: 'linear-gradient(170deg, #8C7BD8, #2A2560 55%, #13112E)',
    chapter: 4,
    chapterTitle: 'Hacia las estrellas',
    caption: 'Chimeneas calentitas y gatos filósofos.',
    quote: 'Paseé de chimenea en chimenea.',
    stories: [
      'Paseé de chimenea en chimenea, calentándome la barriguita. Un gato me explicó que la noche es para pensar. Luego se durmió.',
      'En un tendedero había calcetines de todos los colores y ninguno emparejado. Me acordé del vecino y sus botones. Algo pasa con las parejas por aquí.',
      'Desde el tejado más alto se veía la montaña. Había una luz en la cima, pequeñita y temblorosa, como alguien que espera a que vayan a buscarle.',
    ],
    plus: false,
    unlockAfterBrightDays: 14,
    lootItems: ['farolillo', 'calcetin', 'ovillo', 'vela', 'reloj'],
    lootFriends: ['hollin'],
  },
  {
    id: 'montana-manta',
    name: 'Montaña de la Manta',
    article: 'la',
    art: 'linear-gradient(165deg, #E6E0FB, #C9BFF2 45%, #8C7BD8)',
    chapter: 4,
    chapterTitle: 'Hacia las estrellas',
    caption: 'La nieve de aquí abriga en vez de enfriar.',
    quote: 'La nieve estaba calentita. Te lo juro.',
    stories: [
      'La nieve de esta montaña estaba calentita. Te lo juro. Hice un muñeco y me dio las gracias con un abrazo muy suave.',
      'Subí despacito, con muchas paradas para mirar el paisaje. Bueno, y para descansar. Sobre todo para descansar.',
      'Casi en la cima encontré unas huellas diminutas en forma de estrella. Iban hacia un jardín escondido entre las nubes. Mañana, si brillo, voy.',
    ],
    plus: false,
    unlockAfterBrightDays: 16,
    lootItems: ['bufanda', 'piedra', 'cristal', 'pina'],
    lootFriends: ['nubecilla'],
  },
  {
    id: 'jardin-estrellas',
    name: 'Jardín de las Estrellas Caídas',
    article: 'el',
    art: 'linear-gradient(165deg, #FFE3A3, #C9BFF2 45%, #2A2560)',
    chapter: 4,
    chapterTitle: 'Hacia las estrellas',
    caption: 'Donde descansan las estrellas que se caen.',
    quote: 'La encontré. Y también me encontró ella.',
    stories: [
      'Por fin la encontré: una estrellita pequeña, sentada entre flores de luna. Se había caído y le daba vergüenza volver. Le dije que a mí también me pasa, y se rio.',
      'Las cartas, las barcas, el polvo dorado: era ella, dejando pistas por si alguien la buscaba. Y yo la buscaba. La encontré, y también me encontró ella.',
      'Hoy estuvimos brillando juntas en el jardín. Dice que no tiene prisa por subir al cielo, que aquí abajo se está muy bien. Le he hablado de ti.',
    ],
    plus: false,
    unlockAfterBrightDays: 20,
    lootItems: ['polvo-estrella', 'trocito-luna', 'flor-luna', 'farolillo', 'semilla'],
    lootFriends: ['estrellita'],
  },
  {
    id: 'observatorio-cometas',
    name: 'Observatorio de los Cometas',
    article: 'el',
    art: 'linear-gradient(160deg, #9FE3F0, #2A2560 55%, #13112E)',
    chapter: 4,
    chapterTitle: 'Hacia las estrellas',
    caption: 'Una cúpula vieja que aún mira hacia arriba.',
    quote: 'Conté cometas hasta quedarme dormida.',
    stories: [
      'El observatorio está abandonado, pero el telescopio sigue apuntando al cielo por costumbre. Conté cometas hasta quedarme dormida.',
      'Un mochuelo astrónomo apunta las estrellas en un cuaderno. Me enseñó un hueco en una constelación: falta una, pequeñita. Dice que volverá cuando quiera.',
      'Arreglé la cúpula con un engranaje del mercadillo. Se abrió con un crujido larguísimo y entró tanta luz que parecía de día.',
    ],
    plus: true,
    unlockAfterBrightDays: 15,
    lootItems: ['catalejo', 'engranaje', 'polvo-estrella', 'trocito-luna'],
    lootFriends: ['mochuelito'],
  },
];

export const destinationById = (id: string) => DESTINATIONS.find((d) => d.id === id);

/** "del Bosque de Musgo", "de la Colina…", "de los…", "de las Cuevas…". */
export function fromDestination(d: Pick<Destination, 'name' | 'article'>): string {
  return d.article === 'el' ? `del ${d.name}` : `de ${d.article} ${d.name}`;
}

/** "el Bosque de Musgo", "las Cuevas de Cristal". */
export function withArticle(d: Pick<Destination, 'name' | 'article'>): string {
  return `${d.article} ${d.name}`;
}
