/**
 * Textos de la landing en los otros idiomas. Cada fila: [español, inglés, chino, hindi, francés].
 * El español es la clave: es el texto que hay en index.html y main.js. `i18n.js` traduce la
 * página según el idioma del navegador (o ?lang=xx).
 */
window.LUMI_ROWS = [
  // ── Cabecera y metadatos ──
  ['Lumi, la mascota que brilla cuando sueltas el móvil', 'Lumi, the pet that shines when you put your phone down', 'Lumi：你放下手机，她就发光', 'Lumi, वो पालतू जो फ़ोन रखते ही चमकती है', 'Lumi, la mascotte qui brille quand tu poses ton téléphone'],
  ['Lumi es un espíritu de luz que vive contigo todo el día. Cuanto menos scroll, más brilla y más lejos se va de aventura. Apúntate a la lista de espera para iPhone.', 'Lumi is a light spirit that lives with you all day. The less you scroll, the brighter she shines and the further she goes on adventures. Join the iPhone waitlist.', 'Lumi 是一个整天陪着你的光之精灵。你刷得越少，她就越亮，冒险走得越远。加入 iPhone 等候名单。', 'Lumi रोशनी की एक आत्मा है जो पूरे दिन तुम्हारे साथ रहती है। जितना कम स्क्रॉल, उतनी ज़्यादा चमक और उतना दूर उसका सफ़र। iPhone की प्रतीक्षा सूची में नाम लिखवाओ।', 'Lumi est un esprit de lumière qui vit avec toi toute la journée. Moins tu scrolles, plus elle brille et plus elle part loin à l’aventure. Inscris-toi à la liste d’attente pour iPhone.'],
  ['Lumi: cuando sueltas el móvil, brilla y sale de aventura', 'Lumi: put your phone down and she shines and goes on adventures', 'Lumi：你放下手机，她就发光、出发冒险', 'Lumi: फ़ोन रखो, वो चमकती है और सफ़र पर निकलती है', 'Lumi : pose ton téléphone, elle brille et part à l’aventure'],
  ['Una mascota de luz para pasar menos rato en el móvil. Sin temporizadores y sin culpa.', 'A pet made of light to help you spend less time on your phone. No timers, no guilt.', '一只光之宠物，帮你少看手机。没有计时器，没有愧疚感。', 'रोशनी का एक पालतू, ताकि फ़ोन पर कम समय बीते। न टाइमर, न अपराधबोध।', 'Une mascotte de lumière pour passer moins de temps sur ton téléphone. Sans minuteur et sans culpabilité.'],
  ['Saltar al contenido', 'Skip to content', '跳到正文', 'सामग्री पर जाओ', 'Aller au contenu'],
  ['Lumi, inicio', 'Lumi, home', 'Lumi，首页', 'Lumi, होम', 'Lumi, accueil'],
  ['Llega pronto a iPhone', 'Coming soon to iPhone', '即将登陆 iPhone', 'जल्द ही iPhone पर', 'Bientôt sur iPhone'],

  // ── Hero y formulario ──
  ['Cuando sueltas el móvil, Lumi brilla y sale de aventura.', 'When you put your phone down, Lumi shines and goes on adventures.', '你放下手机，Lumi 就会发光，出发去冒险。', 'जब तुम फ़ोन रखते हो, Lumi चमकती है और सफ़र पर निकलती है।', 'Quand tu poses ton téléphone, Lumi brille et part à l’aventure.'],
  ['Una mascota de luz que vive contigo todo el día. Cuanto menos scroll, más brilla. Y si te pasas, no te riñe: se echa la siesta.', 'A pet made of light that lives with you all day. The less you scroll, the brighter she shines. And if you overdo it, she doesn’t scold you: she takes a nap.', '一只整天陪着你的光之宠物。刷得越少，她越亮。就算你刷过头了，她也不会怪你：她只是去睡个午觉。', 'रोशनी का एक पालतू जो पूरे दिन तुम्हारे साथ रहता है। जितना कम स्क्रॉल, उतनी ज़्यादा चमक। और अगर ज़्यादा हो जाए, तो वो डाँटती नहीं: झपकी ले लेती है।', 'Une mascotte de lumière qui vit avec toi toute la journée. Moins tu scrolles, plus elle brille. Et si tu exagères, elle ne te gronde pas : elle fait la sieste.'],
  ['Tu correo', 'Your email', '你的邮箱', 'तुम्हारा ईमेल', 'Ton e-mail'],
  ['tu@correo.com', 'you@email.com', 'you@email.com', 'you@email.com', 'toi@email.com'],
  ['¿Qué app te roba más tiempo?', 'Which app steals the most time?', '哪个 App 最偷你的时间？', 'कौन-सी ऐप सबसे ज़्यादा समय चुराती है?', 'Quelle appli te vole le plus de temps ?'],
  ['(opcional)', '(optional)', '（可选）', '(वैकल्पिक)', '(facultatif)'],
  ['Elige una', 'Pick one', '选一个', 'एक चुनो', 'Choisis-en une'],
  ['Otra', 'Other', '其他', 'कोई और', 'Autre'],
  ['Apuntarme a la lista', 'Join the list', '加入名单', 'सूची में नाम लिखवाओ', 'M’inscrire à la liste'],
  ['Te escribimos cuando Lumi esté lista, y poco más. Al apuntarte aceptas la', 'We’ll write when Lumi is ready, and not much else. By signing up you accept the', 'Lumi 准备好时我们会写信给你，其他时候不打扰。登记即表示你同意', 'Lumi तैयार होने पर हम तुम्हें लिखेंगे, और बस इतना ही। नाम लिखवाकर तुम स्वीकार करते हो', 'On t’écrit quand Lumi sera prête, et c’est à peu près tout. En t’inscrivant, tu acceptes la'],
  ['política de privacidad', 'privacy policy', '隐私政策', 'गोपनीयता नीति', 'politique de confidentialité'],
  ['Lumi, una criatura redonda de color lavanda con dos antenas de luz ámbar, sonriendo con los brazos en alto', 'Lumi, a round lavender creature with two amber light antennae, smiling with her arms up', 'Lumi，一个圆圆的薰衣草色小家伙，头上有两根琥珀色的光之触角，举着双手微笑', 'Lumi, लैवेंडर रंग का एक गोल जीव, जिसके दो एम्बर रोशनी वाले एंटीना हैं, हाथ ऊपर करके मुस्कुराता हुआ', 'Lumi, une créature ronde couleur lavande avec deux antennes de lumière ambrée, souriante, les bras en l’air'],

  // ── Cómo funciona ──
  ['Tu atención es luz', 'Your attention is light', '你的注意力就是光', 'तुम्हारा ध्यान ही रोशनी है', 'Ton attention, c’est de la lumière'],
  ['Eliges las apps que te enganchan y un límite suave para el día. Lumi no cuenta minutos para echártelos en cara: solo brilla más o menos según cómo vaya la cosa.', 'You pick the apps that hook you and a gentle limit for the day. Lumi doesn’t count minutes to throw them in your face: she just shines more or less depending on how things go.', '你选出最让你上瘾的 App，再定一个温和的每日上限。Lumi 不会数着分钟来数落你：她只是根据情况亮一点或暗一点。', 'तुम वो ऐप्स चुनते हो जो तुम्हें बाँध लेती हैं, और दिन के लिए एक नरम सीमा। Lumi मिनट गिनकर ताने नहीं देती: बस हालात के हिसाब से कम या ज़्यादा चमकती है।', 'Tu choisis les applis qui te happent et une limite douce pour la journée. Lumi ne compte pas les minutes pour te les reprocher : elle brille juste plus ou moins selon comment ça se passe.'],
  ['Toca un momento del día y mira qué hace Lumi.', 'Tap a moment of the day and see what Lumi does.', '点一个时段，看看 Lumi 在做什么。', 'दिन का कोई पल चुनो और देखो Lumi क्या करती है।', 'Touche un moment de la journée et regarde ce que fait Lumi.'],
  ['Casi sin móvil', 'Barely any phone', '几乎没看手机', 'फ़ोन लगभग नहीं', 'Presque pas de téléphone'],
  ['Un ratito', 'A little while', '看了一会儿', 'थोड़ी देर', 'Un petit moment'],
  ['Bastante', 'Quite a bit', '看了挺久', 'काफ़ी', 'Pas mal'],
  ['Me he pasado', 'I overdid it', '看过头了', 'ज़्यादा हो गया', 'J’ai abusé'],
  ['Nunca enferma y nunca muere. Cada día empieza de cero.', 'She never gets sick and never dies. Every day starts fresh.', '她永远不会生病，也永远不会死。每天都是新的开始。', 'वो कभी बीमार नहीं होती और कभी मरती नहीं। हर दिन नई शुरुआत है।', 'Elle ne tombe jamais malade et ne meurt jamais. Chaque jour repart de zéro.'],
  ['Luz de hoy', 'Today’s light', '今天的光', 'आज की रोशनी', 'Lumière du jour'],
  ['Brilla a tope', 'Shining bright', '亮到最亮', 'पूरी चमक', 'Brille à fond'],
  ['Brilla bien', 'Shining well', '亮得不错', 'अच्छी चमक', 'Brille bien'],
  ['Se está apagando', 'Fading', '慢慢变暗', 'मद्धम हो रही है', 'S’éteint peu à peu'],
  ['Luz mínima', 'Minimal light', '最微弱的光', 'बहुत कम रोशनी', 'Lumière minimale'],
  ['¡Hoy me voy al Bosque de Musgo! Te traigo algo.', 'I’m off to the Moss Forest today! I’ll bring you something.', '我今天要去苔藓森林！给你带点东西回来。', 'आज मैं काई वाले जंगल जा रही हूँ! तुम्हारे लिए कुछ लाऊँगी।', 'Aujourd’hui, je pars au Bois de Mousse ! Je te rapporte quelque chose.'],
  ['Sigo de aventura. Voy tarareando.', 'Still on my adventure. Humming along.', '我还在冒险，一边走一边哼歌。', 'अभी सफ़र पर हूँ। गुनगुनाती जा रही हूँ।', 'Je continue l’aventure. Je fredonne.'],
  ['Uaaah… Hoy mejor me quedo en casa.', 'Yaaawn… I’d better stay home today.', '哈啊……今天还是待在家吧。', 'उआँह… आज घर पर ही रहती हूँ।', 'Aaaah… Aujourd’hui, je reste plutôt à la maison.'],
  ['Zzz… Mañana, luz nueva.', 'Zzz… New light tomorrow.', 'Zzz……明天，新的光。', 'Zzz… कल, नई रोशनी।', 'Zzz… Demain, nouvelle lumière.'],
  ['Lumi radiante, brillando a tope', 'Lumi radiant, shining bright', '闪闪发光的 Lumi，亮到最亮', 'जगमग Lumi, पूरी चमक के साथ', 'Lumi radieuse, qui brille à fond'],
  ['Lumi contenta, sonriendo', 'Lumi happy, smiling', '开心的 Lumi，在微笑', 'ख़ुश Lumi, मुस्कुराती हुई', 'Lumi contente, souriante'],
  ['Lumi cansada, bostezando', 'Lumi tired, yawning', '累了的 Lumi，在打哈欠', 'थकी हुई Lumi, जम्हाई लेती हुई', 'Lumi fatiguée, qui bâille'],
  ['Lumi apagadita, dormida hecha una bolita', 'Lumi dim, asleep curled up in a ball', '暗暗的 Lumi，蜷成一团睡着了', 'मद्धम Lumi, गेंद की तरह सिकुड़कर सोई हुई', 'Lumi éteinte, endormie en boule'],
  ['Radiante.', 'Radiant.', '闪闪发光。', 'जगमग।', 'Radieuse.'],
  ['Brilla a tope y sale de expedición.', 'Shining bright and off on an expedition.', '亮到最亮，出发去探险。', 'पूरी चमक के साथ सफ़र पर निकलती है।', 'Elle brille à fond et part en expédition.'],
  ['<b>Radiante.</b> Brilla a tope y sale de expedición.', '<b>Radiant.</b> Shining bright and off on an expedition.', '<b>闪闪发光。</b>亮到最亮，出发去探险。', '<b>जगमग।</b> पूरी चमक के साथ सफ़र पर निकलती है।', '<b>Radieuse.</b> Elle brille à fond et part en expédition.'],
  ['<b>Contenta.</b> Sigue explorando, tan a gusto.', '<b>Happy.</b> Still exploring, having a lovely time.', '<b>开心。</b>继续探险，自在得很。', '<b>ख़ुश।</b> मज़े से घूम रही है।', '<b>Contente.</b> Elle continue d’explorer, bien tranquille.'],
  ['<b>Cansada.</b> Bosteza y se queda en casa esperándote.', '<b>Tired.</b> She yawns and stays home waiting for you.', '<b>有点累。</b>打着哈欠，待在家里等你。', '<b>थकी हुई।</b> जम्हाई लेती है और घर पर तुम्हारा इंतज़ार करती है।', '<b>Fatiguée.</b> Elle bâille et reste à la maison à t’attendre.'],
  ['<b>Apagadita.</b> Se echa la siesta hecha una bolita. Mañana se despierta con toda su luz.', '<b>Dim.</b> She naps curled up in a ball. Tomorrow she wakes up with all her light.', '<b>暗暗的。</b>蜷成一团睡午觉。明天醒来，光又满满的。', '<b>मद्धम।</b> गेंद की तरह सिकुड़कर झपकी लेती है। कल पूरी रोशनी के साथ जागेगी।', '<b>Éteinte.</b> Elle fait la sieste roulée en boule. Demain, elle se réveille avec toute sa lumière.'],

  // ── Escudo ──
  ['«Lumi se estaba echando la siesta… ¿de verdad entramos?»', '“Lumi was taking a nap… are we really going in?”', '“Lumi 正在打盹呢……真的要进去吗？”', '“Lumi झपकी ले रही थी… सच में अंदर जाएँ?”', '« Lumi faisait la sieste… on y va vraiment ? »'],
  ['Cuando ya has pasado tu límite y abres una app ladrona, no sale una pantalla gris de «acceso denegado». Sale Lumi, medio dormida, y te lo pregunta.', 'When you’re past your limit and open a thief app, you don’t get a grey “access denied” screen. You get Lumi, half asleep, asking you.', '当你超过上限、又打开偷时间的 App 时，不会出现冷冰冰的“禁止访问”灰屏。出现的是半睡半醒的 Lumi，轻声问你。', 'जब तुम सीमा पार करके कोई चोर ऐप खोलते हो, तो "पहुँच नहीं" वाली धूसर स्क्रीन नहीं आती। आधी नींद में Lumi आती है और तुमसे पूछती है।', 'Quand tu as dépassé ta limite et que tu ouvres une appli voleuse, pas d’écran gris « accès refusé ». C’est Lumi, à moitié endormie, qui te pose la question.'],
  ['Puedes entrar igualmente. Solo que ahora alguien te está mirando con esos ojitos.', 'You can still go in. It’s just that now someone is looking at you with those little eyes.', '你还是可以进去。只是现在，有人正用那双小眼睛看着你。', 'तुम फिर भी अंदर जा सकते हो। बस अब कोई उन नन्ही आँखों से तुम्हें देख रहा है।', 'Tu peux quand même y aller. Sauf que maintenant, quelqu’un te regarde avec ces petits yeux.'],
  ['Instagram está tapada hasta mañana', 'Instagram is tucked in until tomorrow', 'Instagram 盖上被子了，明天见', 'Instagram कल तक ढकी हुई है', 'Instagram est bordée jusqu’à demain'],
  ['Lumi dormida hecha una bolita, con las antenas apenas encendidas', 'Lumi asleep curled up in a ball, her antennae barely lit', 'Lumi 蜷成一团睡着了，触角只亮着一点点', 'Lumi गेंद की तरह सिकुड़कर सोई हुई, एंटीना बस हल्के-से जले हुए', 'Lumi endormie en boule, les antennes à peine allumées'],
  ['Lumi se estaba echando la siesta… ¿de verdad entramos?', 'Lumi was taking a nap… are we really going in?', 'Lumi 正在打盹呢……真的要进去吗？', 'Lumi झपकी ले रही थी… सच में अंदर जाएँ?', 'Lumi faisait la sieste… on y va vraiment ?'],
  ['Ya habéis pasado de tu hora de hoy. Si lo dejas ahora, mañana se despierta con más luz.', 'You’ve gone past today’s time. If you stop now, she’ll wake up brighter tomorrow.', '今天的时间已经用完了。现在放下，她明天醒来会更亮。', 'आज का समय पूरा हो चुका है। अभी छोड़ दो, तो कल वो और ज़्यादा रोशनी के साथ जागेगी।', 'Vous avez dépassé ton temps du jour. Si tu arrêtes maintenant, elle se réveillera plus lumineuse demain.'],
  ['Vale, lo dejo', 'Okay, I’ll stop', '好，我放下', 'ठीक है, छोड़ देते हैं', 'D’accord, j’arrête'],
  ['5 min más', '5 more min', '再 5 分钟', '5 मिनट और', '5 min de plus'],
  ['Gracias. Me quedo soñando contigo 💤', 'Thank you. I’ll keep dreaming of you 💤', '谢谢你。我继续梦见你 💤', 'शुक्रिया। मैं तुम्हारे सपने देखती रहूँगी 💤', 'Merci. Je continue à rêver de toi 💤'],
  ['Vale, 5 minutitos. Aquí te espero 🌙', 'Okay, 5 little minutes. I’ll wait here 🌙', '好，5 分钟。我在这儿等你 🌙', 'ठीक है, 5 मिनट। मैं यहीं इंतज़ार करूँगी 🌙', 'D’accord, 5 petites minutes. Je t’attends ici 🌙'],
  ['Otros 5, vale. Te espero despierta 🌙', 'Another 5, okay. I’ll wait up for you 🌙', '再 5 分钟，好吧。我醒着等你 🌙', 'और 5, ठीक है। मैं जागकर इंतज़ार करूँगी 🌙', 'Encore 5, d’accord. Je t’attends réveillée 🌙'],
  ['Vale… 5 min, pero te espero despierta', 'Okay… 5 min, but I’ll wait up for you', '好吧……5 分钟，我醒着等你', 'ठीक है… 5 मिनट, पर मैं जागकर इंतज़ार करूँगी', 'D’accord… 5 min, mais je t’attends réveillée'],

  // ── Postales ──
  ['Cada noche vuelve con una postal', 'Every night she comes back with a postcard', '每天晚上，她都会带着明信片回来', 'हर रात वो एक पोस्टकार्ड लेकर लौटती है', 'Chaque soir, elle rentre avec une carte postale'],
  ['Los días que brilla, Lumi se va de expedición. Por la noche te escribe desde donde ha estado, y trae objetos raros para su colección.', 'On the days she shines, Lumi goes on an expedition. At night she writes to you from wherever she’s been, and brings back odd things for her collection.', '发光的日子里，Lumi 会出发探险。晚上，她从去过的地方给你写信，还带回稀奇古怪的东西放进收藏。', 'जिन दिनों वो चमकती है, Lumi सफ़र पर जाती है। रात को वो जहाँ गई थी वहाँ से तुम्हें लिखती है, और अपने संग्रह के लिए अजीब-अजीब चीज़ें लाती है।', 'Les jours où elle brille, Lumi part en expédition. Le soir, elle t’écrit de là où elle est allée, et rapporte des objets bizarres pour sa collection.'],
  ['La entrada redonda de una madriguera en una colina de musgo, de noche', 'The round entrance of a burrow in a mossy hill, at night', '夜晚，长满苔藓的小山坡上，一个圆圆的洞口', 'रात में, काई वाली पहाड़ी पर एक बिल का गोल दरवाज़ा', 'L’entrée ronde d’un terrier dans une colline moussue, la nuit'],
  ['Bosque de Musgo', 'Moss Forest', '苔藓森林', 'काई वाला जंगल', 'Bois de Mousse'],
  ['Me eché una siesta sin querer. Cuando me desperté, alguien me había tapado con una hoja.', 'I dozed off without meaning to. When I woke up, someone had tucked me in with a leaf.', '我一不小心就睡着了。醒来的时候，有人用一片叶子给我盖好了。', 'मैं अनजाने में सो गई। जब उठी, तो किसी ने मुझे एक पत्ते से ढक दिया था।', 'Je me suis endormie sans le vouloir. À mon réveil, quelqu’un m’avait couverte d’une feuille.'],
  ['Una luna creciente sobre un cielo índigo lleno de estrellas', 'A crescent moon over an indigo sky full of stars', '靛蓝色的星空中，挂着一弯新月', 'तारों से भरे नीले आसमान पर एक अर्धचंद्र', 'Un croissant de lune dans un ciel indigo plein d’étoiles'],
  ['Lago de las Lunas', 'Lake of Moons', '月亮湖', 'चाँदों वाली झील', 'Lac des Lunes'],
  ['Había dos lunas y ninguna era de queso.', 'There were two moons and neither was made of cheese.', '有两个月亮，哪个都不是奶酪做的。', 'दो चाँद थे और कोई भी पनीर का नहीं था।', 'Il y avait deux lunes et aucune n’était en fromage.'],
  ['Setas que brillan entre la hierba y flores de color melocotón', 'Mushrooms glowing in the grass among peach-colored flowers', '草丛里发光的蘑菇和蜜桃色的小花', 'घास के बीच चमकते कुकुरमुत्ते और आड़ू रंग के फूल', 'Des champignons qui brillent dans l’herbe parmi des fleurs couleur pêche'],
  ['Jardín de Setas', 'Mushroom Garden', '蘑菇花园', 'कुकुरमुत्तों का बाग़', 'Jardin des Champignons'],
  ['Una seta me guiñó un ojo. Creo.', 'A mushroom winked at me. I think.', '有一朵蘑菇朝我眨了眨眼。大概吧。', 'एक कुकुरमुत्ते ने मुझे आँख मारी। शायद।', 'Un champignon m’a fait un clin d’œil. Je crois.'],
  ['20 lugares por descubrir', '20 places to discover', '20 个地方等你发现', 'खोजने के लिए 20 जगहें', '20 lieux à découvrir'],
  ['Del Bosque de Musgo al Observatorio de los Cometas. Las postales cuentan una historia por capítulos: una estrellita se ha caído del cielo y Lumi va siguiendo sus pistas.', 'From the Moss Forest to the Comet Observatory. The postcards tell a story in chapters: a little star has fallen from the sky and Lumi follows her clues.', '从苔藓森林到彗星天文台。明信片按章节讲一个故事：一颗小星星从天上掉了下来，Lumi 一路追寻她留下的线索。', 'काई वाले जंगल से पुच्छल तारों की वेधशाला तक। पोस्टकार्ड अध्यायों में एक कहानी सुनाते हैं: एक नन्हा तारा आसमान से गिर गया है और Lumi उसके सुराग़ों के पीछे चलती है।', 'Du Bois de Mousse à l’Observatoire des Comètes. Les cartes racontent une histoire en chapitres : une petite étoile est tombée du ciel et Lumi suit ses indices.'],
  ['Lumi gana chispas explorando, y pronto podrá gastarlas en decorar su casa. No se compran. Se brillan.', 'Lumi earns sparks by exploring, and soon she’ll be able to spend them decorating her home. They can’t be bought. They’re shone.', 'Lumi 靠探险赚火花，很快就能用来装饰自己的家。火花买不到，只能靠发光得到。', 'Lumi घूमकर चिंगारियाँ कमाती है, और जल्द ही उनसे अपना घर सजा सकेगी। ये ख़रीदी नहीं जातीं। चमककर कमाई जाती हैं।', 'Lumi gagne des étincelles en explorant, et bientôt elle pourra les dépenser pour décorer sa maison. Elles ne s’achètent pas. Elles se brillent.'],
  ['Un álbum que se va llenando', 'An album that keeps filling up', '一本慢慢装满的相册', 'एक एल्बम जो भरता जाता है', 'Un album qui se remplit'],
  ['Postales, objetos (un trébol de tres hojas muy simpático, un calcetín perdido) y criaturas amigas que se va encontrando.', 'Postcards, things (a very friendly three-leaf clover, a lost sock) and creature friends she meets along the way.', '明信片、小物件（一片很可爱的三叶草、一只落单的袜子），还有一路遇到的小伙伴。', 'पोस्टकार्ड, चीज़ें (तीन पत्तियों वाला एक बहुत प्यारा तिपतिया, एक खोया मोज़ा) और रास्ते में मिलने वाले जीव दोस्त।', 'Des cartes, des objets (un trèfle à trois feuilles très sympathique, une chaussette perdue) et des créatures amies rencontrées en chemin.'],
  ['Chispas, nunca dinero', 'Sparks, never money', '火花，不是钱', 'चिंगारियाँ, पैसे कभी नहीं', 'Des étincelles, jamais d’argent'],
  ['El resumen semanal de Lumi en formato vertical, listo para compartir en stories', 'Lumi’s weekly summary in vertical format, ready to share in stories', 'Lumi 的竖版每周总结，可以直接分享到快拍', 'Lumi का साप्ताहिक सारांश, खड़े फ़ॉर्मेट में, स्टोरी में शेयर करने के लिए तैयार', 'Le bilan de la semaine de Lumi au format vertical, prêt à partager en story'],
  ['Tu semana con Lumi', 'Your week with Lumi', '你和 Lumi 的一周', 'Lumi के साथ तुम्हारा हफ़्ता', 'Ta semaine avec Lumi'],
  ['5 días brillando', '5 days shining', '发光 5 天', '5 दिन चमक', '5 jours à briller'],
  ['3 postales nuevas. Y un calcetín.', '3 new postcards. And a sock.', '3 张新明信片。还有一只袜子。', '3 नए पोस्टकार्ड। और एक मोज़ा।', '3 nouvelles cartes. Et une chaussette.'],
  ['Y los domingos, tu semana en una story', 'And on Sundays, your week in a story', '每到周日，把你的一周做成一条快拍', 'और रविवार को, तुम्हारा हफ़्ता एक स्टोरी में', 'Et le dimanche, ta semaine en story'],
  ['Un resumen vertical con lo que ha brillado Lumi y las postales que ha traído, listo para compartir. Sin minutos exactos ni gráficas de culpa.', 'A vertical summary of how much Lumi shone and the postcards she brought, ready to share. No exact minutes and no guilt charts.', '一张竖版总结，记下 Lumi 亮了多少、带回了哪些明信片，可以直接分享。没有精确的分钟数，也没有让人愧疚的图表。', 'एक खड़ा सारांश कि Lumi कितना चमकी और कौन-से पोस्टकार्ड लाई, शेयर करने के लिए तैयार। न सटीक मिनट, न अपराधबोध वाले चार्ट।', 'Un bilan vertical avec tout ce que Lumi a brillé et les cartes qu’elle a rapportées, prêt à partager. Sans minutes exactes ni graphiques culpabilisants.'],

  // ── No es un temporizador ──
  ['No es un temporizador. Es alguien que vive contigo.', 'It’s not a timer. It’s someone who lives with you.', '她不是计时器，而是和你住在一起的伙伴。', 'यह टाइमर नहीं है। यह कोई है जो तुम्हारे साथ रहता है।', 'Ce n’est pas un minuteur. C’est quelqu’un qui vit avec toi.'],
  ['Diferencias entre un temporizador de concentración y Lumi', 'Differences between a focus timer and Lumi', '专注计时器和 Lumi 的区别', 'फ़ोकस टाइमर और Lumi में फ़र्क़', 'Différences entre un minuteur de concentration et Lumi'],
  ['Con un temporizador', 'With a timer', '用计时器', 'टाइमर के साथ', 'Avec un minuteur'],
  ['Con Lumi', 'With Lumi', '有 Lumi', 'Lumi के साथ', 'Avec Lumi'],
  ['Tienes que acordarte de empezar una sesión.', 'You have to remember to start a session.', '你得记得开始一次专注。', 'तुम्हें सत्र शुरू करना याद रखना पड़ता है।', 'Tu dois penser à lancer une session.'],
  ['Lumi ya está ahí, todo el día, sin que hagas nada.', 'Lumi is already there, all day, without you doing anything.', 'Lumi 一直都在，整天陪着你，什么都不用做。', 'Lumi पहले से वहाँ है, पूरे दिन, बिना तुम्हारे कुछ किए।', 'Lumi est déjà là, toute la journée, sans que tu fasses rien.'],
  ['Si lo dejas a medias, se rompe la racha.', 'If you stop halfway, the streak breaks.', '半途而废，连续记录就断了。', 'बीच में छोड़ा, तो सिलसिला टूट जाता है।', 'Si tu t’arrêtes en cours, la série est cassée.'],
  ['Si te pasas, se duerme. Las rachas perdonan los días de descanso.', 'If you overdo it, she falls asleep. Streaks forgive rest days.', '刷过头了，她就睡着。连续记录会原谅休息日。', 'ज़्यादा हो जाए, तो वो सो जाती है। सिलसिले आराम के दिनों को माफ़ कर देते हैं।', 'Si tu exagères, elle s’endort. Les séries pardonnent les jours de repos.'],
  ['Una pantalla que te dice que no.', 'A screen that tells you no.', '一块对你说“不”的屏幕。', 'एक स्क्रीन जो तुम्हें ना कहती है।', 'Un écran qui te dit non.'],
  ['Una carita que te pregunta si de verdad.', 'A little face asking if you really mean it.', '一张小脸问你：真的吗？', 'एक नन्हा चेहरा जो पूछता है: सच में?', 'Une petite frimousse qui te demande : vraiment ?'],
  ['Los bloqueadores y los temporizadores le funcionan a mucha gente. Lumi es para quien prefiere que le cuiden a que le vigilen.', 'Blockers and timers work for lots of people. Lumi is for those who’d rather be cared for than watched.', '屏蔽器和计时器对很多人有用。Lumi 是给那些更想被照顾、而不是被监视的人。', 'ब्लॉकर और टाइमर बहुत लोगों के काम आते हैं। Lumi उनके लिए है जिन्हें निगरानी से ज़्यादा देखभाल पसंद है।', 'Les bloqueurs et les minuteurs marchent pour beaucoup de gens. Lumi est pour celles et ceux qui préfèrent qu’on prenne soin d’eux plutôt qu’on les surveille.'],

  // ── Privacidad ──
  ['Lumi no ve lo que haces dentro de tus apps', 'Lumi doesn’t see what you do inside your apps', 'Lumi 看不到你在 App 里做什么', 'Lumi नहीं देखती कि तुम ऐप्स के अंदर क्या करते हो', 'Lumi ne voit pas ce que tu fais dans tes applis'],
  ['Usa Tiempo de uso de Apple.', 'It uses Apple’s Screen Time.', '使用 Apple 的屏幕使用时间。', 'यह Apple का स्क्रीन टाइम इस्तेमाल करती है।', 'Elle utilise Temps d’écran d’Apple.'],
  ['Lumi solo recibe avisos del tipo «ya vas por la mitad de tu límite». No sabe qué vídeos ves ni con quién hablas. Tampoco podría: iOS no lo permite.', 'Lumi only gets notices like “you’re halfway through your limit”. She doesn’t know what videos you watch or who you talk to. She couldn’t anyway: iOS doesn’t allow it.', 'Lumi 只会收到类似“你已经用了一半上限”的提醒。她不知道你看了什么视频、和谁聊天。她也做不到：iOS 不允许。', 'Lumi को बस ऐसी सूचनाएँ मिलती हैं: "तुम अपनी सीमा के आधे पर पहुँच गए हो"। उसे नहीं पता कि तुम कौन-से वीडियो देखते हो या किससे बात करते हो। वो जान भी नहीं सकती: iOS इसकी इजाज़त नहीं देता।', 'Lumi reçoit seulement des avis du type « tu es à la moitié de ta limite ». Elle ne sait pas quelles vidéos tu regardes ni avec qui tu parles. Elle ne pourrait pas : iOS ne le permet pas.'],
  ['Lo que sabe de ti vive en tu iPhone.', 'What she knows about you lives on your iPhone.', '她对你的了解只保存在你的 iPhone 上。', 'वो तुम्हारे बारे में जो जानती है, वो तुम्हारे iPhone पर रहता है।', 'Ce qu’elle sait de toi reste sur ton iPhone.'],
  ['Su nombre, tu límite y tus postales. Sin cuentas obligatorias.', 'Her name, your limit and your postcards. No mandatory accounts.', '她的名字、你的上限和你的明信片。不强制注册账户。', 'उसका नाम, तुम्हारी सीमा और तुम्हारे पोस्टकार्ड। खाता ज़रूरी नहीं।', 'Son nom, ta limite et tes cartes. Aucun compte obligatoire.'],
  ['Tu correo, solo para esto.', 'Your email, only for this.', '你的邮箱，只用于这件事。', 'तुम्हारा ईमेल, सिर्फ़ इसके लिए।', 'Ton e-mail, seulement pour ça.'],
  ['Lo usamos para avisarte cuando Lumi esté lista. No lo vendemos ni lo compartimos, y te das de baja cuando quieras.', 'We use it to let you know when Lumi is ready. We don’t sell or share it, and you can unsubscribe whenever you want.', '我们只用它在 Lumi 准备好时通知你。不会出售或分享，你随时可以退订。', 'हम इसका इस्तेमाल सिर्फ़ यह बताने के लिए करते हैं कि Lumi तैयार है। हम इसे न बेचते हैं न साझा करते हैं, और तुम जब चाहो सदस्यता छोड़ सकते हो।', 'On l’utilise pour te prévenir quand Lumi sera prête. On ne le vend pas, on ne le partage pas, et tu te désinscris quand tu veux.'],

  // ── Precio ──
  ['Lo importante es gratis. Siempre.', 'The important stuff is free. Always.', '重要的东西永远免费。', 'ज़रूरी चीज़ें मुफ़्त हैं। हमेशा।', 'L’essentiel est gratuit. Toujours.'],
  ['Lumi te acompaña igual pagues o no. Plus es para quien quiere ir un poco más lejos.', 'Lumi stays with you whether you pay or not. Plus is for those who want to go a little further.', '不管付不付费，Lumi 都一样陪着你。Plus 是给想走得更远一点的人。', 'पैसे दो या न दो, Lumi तुम्हारे साथ रहती है। Plus उनके लिए है जो थोड़ा और आगे जाना चाहते हैं।', 'Lumi t’accompagne que tu paies ou non. Plus, c’est pour qui veut aller un peu plus loin.'],
  ['Gratis', 'Free', '免费', 'मुफ़्त', 'Gratuit'],
  ['0 €, para siempre', '$0, forever', '0 元，永久免费', '₹0, हमेशा के लिए', '0 €, pour toujours'],
  ['Tu Lumi y su escudo', 'Your Lumi and her shield', '你的 Lumi 和她的护盾', 'तुम्हारी Lumi और उसकी ढाल', 'Ta Lumi et son bouclier'],
  ['El límite diario', 'The daily limit', '每日上限', 'रोज़ की सीमा', 'La limite quotidienne'],
  ['Expediciones y postales', 'Expeditions and postcards', '探险和明信片', 'सफ़र और पोस्टकार्ड', 'Expéditions et cartes postales'],
  ['El widget', 'The widget', '小组件', 'विजेट', 'Le widget'],
  ['El modo noche', 'Night mode', '夜间模式', 'रात का मोड', 'Le mode nuit'],
  ['Unos 49,99 € al año, con prueba gratis', 'About $49.99 a year, with a free trial', '每年约 49.99 美元，含免费试用', 'लगभग $49.99 सालाना, मुफ़्त ट्रायल के साथ', 'Environ 49,99 € par an, avec essai gratuit'],
  ['Zonas exclusivas, con sus propias historias', 'Exclusive places, with their own stories', '专属地点，有自己的故事', 'ख़ास जगहें, अपनी कहानियों के साथ', 'Des lieux exclusifs, avec leurs propres histoires'],
  ['Escudo estricto, sin «5 min más»', 'Strict shield, without “5 more min”', '严格护盾，没有“再 5 分钟”', 'सख़्त ढाल, बिना "5 मिनट और"', 'Bouclier strict, sans « 5 min de plus »'],
  ['Tus números: todo lo que habéis brillado juntos', 'Your numbers: everything you’ve shone together', '你的数据：你们一起发过的所有光', 'तुम्हारे आँकड़े: तुम दोनों कितना चमके', 'Tes chiffres : tout ce que vous avez brillé ensemble'],
  ['Precio orientativo. Si cambia, lo sabrás antes que nadie.', 'Approximate price. If it changes, you’ll be the first to know.', '价格仅供参考。如有变化，你会第一个知道。', 'अनुमानित क़ीमत। बदली तो सबसे पहले तुम्हें पता चलेगा।', 'Prix indicatif. S’il change, tu le sauras avant tout le monde.'],

  // ── Preguntas ──
  ['Preguntas que nos hacen', 'Questions people ask us', '大家常问的问题', 'लोग हमसे क्या पूछते हैं', 'Les questions qu’on nous pose'],
  ['¿Cuándo sale?', 'When is it coming out?', '什么时候上线？', 'यह कब आएगी?', 'Quand sort-elle ?'],
  ['Estamos terminando la primera versión para iPhone. Quien esté en la lista la probará antes que nadie, en una beta privada.', 'We’re finishing the first version for iPhone. People on the list will try it before anyone else, in a private beta.', '我们正在完成 iPhone 的第一个版本。名单上的人会最先在私密测试中试用。', 'हम iPhone का पहला संस्करण पूरा कर रहे हैं। सूची में शामिल लोग इसे सबसे पहले एक निजी बीटा में आज़माएँगे।', 'On termine la première version pour iPhone. Les personnes sur la liste l’essaieront avant tout le monde, dans une bêta privée.'],
  ['¿Y para Android?', 'What about Android?', '有安卓版吗？', 'और Android के लिए?', 'Et sur Android ?'],
  ['De momento solo iPhone. Si usas Android, apúntate igual: nos ayuda a saber cuánta gente lo quiere.', 'Only iPhone for now. If you use Android, sign up anyway: it helps us know how many people want it.', '目前只有 iPhone 版。如果你用安卓，也欢迎登记：这能帮我们了解有多少人想要。', 'अभी सिर्फ़ iPhone। अगर तुम Android इस्तेमाल करते हो, तब भी नाम लिखवाओ: इससे हमें पता चलता है कि कितने लोग इसे चाहते हैं।', 'Pour l’instant, seulement iPhone. Si tu es sur Android, inscris-toi quand même : ça nous aide à savoir combien de gens la veulent.'],
  ['¿Me va a bloquear las apps?', 'Will it block my apps?', '它会屏蔽我的 App 吗？', 'क्या यह मेरी ऐप्स ब्लॉक करेगी?', 'Est-ce qu’elle va bloquer mes applis ?'],
  ['Solo las que tú elijas y solo cuando pases tu límite. Siempre tienes salida con «5 min más». Si quieres un escudo sin excusas, el bloqueo estricto es opcional.', 'Only the ones you choose and only when you go past your limit. You always have a way out with “5 more min”. If you want a no-excuses shield, strict blocking is optional.', '只屏蔽你选的 App，而且只在你超过上限时。你随时可以点“再 5 分钟”。如果想要毫无借口的护盾，可以选择严格屏蔽。', 'सिर्फ़ वो जो तुम चुनो, और सिर्फ़ तब जब तुम सीमा पार करो। "5 मिनट और" से तुम्हारे पास हमेशा रास्ता है। बिना बहाने वाली ढाल चाहिए, तो सख़्त ब्लॉक वैकल्पिक है।', 'Seulement celles que tu choisis et seulement quand tu dépasses ta limite. Tu as toujours une sortie avec « 5 min de plus ». Si tu veux un bouclier sans excuses, le blocage strict est facultatif.'],
  ['¿Qué pasa si un día me paso muchísimo?', 'What if I go way over one day?', '如果有一天我刷得特别多怎么办？', 'अगर किसी दिन बहुत ज़्यादा हो जाए तो?', 'Et si un jour j’exagère vraiment ?'],
  ['Que Lumi se duerme. No enferma, no se enfada y no te manda notificaciones pasivo-agresivas. Al día siguiente se despierta con toda su luz.', 'Lumi falls asleep. She doesn’t get sick, doesn’t get angry and doesn’t send you passive-aggressive notifications. The next day she wakes up with all her light.', '那 Lumi 就会睡着。她不会生病，不会生气，也不会给你发阴阳怪气的通知。第二天醒来，她的光又是满满的。', 'तो Lumi सो जाती है। वो बीमार नहीं होती, नाराज़ नहीं होती और तुम्हें ताने वाली सूचनाएँ नहीं भेजती। अगले दिन वो पूरी रोशनी के साथ जागती है।', 'Lumi s’endort. Elle ne tombe pas malade, ne se fâche pas et ne t’envoie pas de notifications passives-agressives. Le lendemain, elle se réveille avec toute sa lumière.'],
  ['¿Lumi sabe qué hago en el móvil?', 'Does Lumi know what I do on my phone?', 'Lumi 知道我在手机上做什么吗？', 'क्या Lumi जानती है कि मैं फ़ोन पर क्या करता हूँ?', 'Lumi sait-elle ce que je fais sur mon téléphone ?'],
  ['No. Solo sabe cuánto de tu límite llevas, a grandes rasgos. Lo que ves, escribes o buscas se queda entre tú y tu iPhone.', 'No. She only roughly knows how much of your limit you’ve used. What you watch, write or search stays between you and your iPhone.', '不知道。她只大概知道你用了多少上限。你看什么、写什么、搜什么，都只留在你和你的 iPhone 之间。', 'नहीं। उसे बस मोटे तौर पर पता है कि तुमने अपनी सीमा का कितना हिस्सा इस्तेमाल किया। तुम क्या देखते, लिखते या खोजते हो, वो तुम्हारे और तुम्हारे iPhone के बीच रहता है।', 'Non. Elle sait seulement, en gros, où tu en es de ta limite. Ce que tu regardes, écris ou cherches reste entre toi et ton iPhone.'],
  ['¿Por qué una mascota y no un contador de horas?', 'Why a pet and not an hour counter?', '为什么是宠物，而不是计时器？', 'घंटे गिनने वाले की जगह पालतू क्यों?', 'Pourquoi une mascotte et pas un compteur d’heures ?'],
  ['Porque es más fácil soltar el móvil por alguien que te cae bien que por un número. Y porque ver a Lumi volver con una postal es mucho más bonito que una gráfica.', 'Because it’s easier to put your phone down for someone you like than for a number. And because seeing Lumi come back with a postcard is much nicer than a chart.', '因为为了一个你喜欢的伙伴放下手机，比为了一个数字容易多了。而且看到 Lumi 带着明信片回来，比看图表美好多了。', 'क्योंकि किसी संख्या से ज़्यादा आसान है किसी प्यारे के लिए फ़ोन रखना। और Lumi को पोस्टकार्ड लेकर लौटते देखना किसी चार्ट से कहीं ज़्यादा सुंदर है।', 'Parce qu’il est plus facile de poser son téléphone pour quelqu’un qu’on aime bien que pour un chiffre. Et parce que voir Lumi rentrer avec une carte, c’est bien plus joli qu’un graphique.'],

  // ── Final y pie ──
  ['Lumi contenta, mirando de frente con las mejillas sonrosadas', 'Lumi happy, looking straight ahead with rosy cheeks', '开心的 Lumi，脸蛋红扑扑地看着你', 'ख़ुश Lumi, गुलाबी गालों के साथ सामने देखती हुई', 'Lumi contente, qui regarde de face, les joues roses'],
  ['Lumi te espera despierta', 'Lumi is waiting up for you', 'Lumi 醒着等你', 'Lumi जागकर तुम्हारा इंतज़ार कर रही है', 'Lumi t’attend réveillée'],
  ['Apúntate y te avisamos en cuanto pueda mudarse a tu iPhone.', 'Sign up and we’ll let you know as soon as she can move into your iPhone.', '登记一下，她一能搬进你的 iPhone，我们就通知你。', 'नाम लिखवाओ और जैसे ही वो तुम्हारे iPhone में आ सकेगी, हम तुम्हें बताएँगे।', 'Inscris-toi et on te prévient dès qu’elle peut emménager dans ton iPhone.'],
  ['Te escribimos cuando Lumi esté lista, y poco más.', 'We’ll write when Lumi is ready, and not much else.', 'Lumi 准备好时我们会写信给你，其他时候不打扰。', 'Lumi तैयार होने पर हम तुम्हें लिखेंगे, और बस इतना ही।', 'On t’écrit quand Lumi sera prête, et c’est à peu près tout.'],
  ['Hecho con cariño y con el móvil boca abajo.', 'Made with love and with the phone face down.', '用心制作，手机屏幕朝下。', 'प्यार से बनाया, फ़ोन को उल्टा रखकर।', 'Fait avec amour et le téléphone face contre table.'],
  ['Ayuda', 'Help', '帮助', 'मदद', 'Aide'],
  ['Privacidad', 'Privacy', '隐私', 'गोपनीयता', 'Confidentialité'],
  ['Términos', 'Terms', '条款', 'शर्तें', 'Conditions'],
  ['¡Ya estás en la lista!', 'You’re on the list!', '你已经在名单上了！', 'तुम सूची में आ गए!', 'Tu es sur la liste !'],
  ['Lumi ha dado tres saltitos. Te escribiremos en cuanto pueda mudarse a tu iPhone.', 'Lumi did three little hops. We’ll write as soon as she can move into your iPhone.', 'Lumi 开心地跳了三下。她一能搬进你的 iPhone，我们就写信告诉你。', 'Lumi तीन बार उछली। जैसे ही वो तुम्हारे iPhone में आ सकेगी, हम तुम्हें लिखेंगे।', 'Lumi a fait trois petits bonds. On t’écrit dès qu’elle peut emménager dans ton iPhone.'],
  ['Invita a alguien que también necesite un Lumi', 'Invite someone who also needs a Lumi', '邀请一个也需要 Lumi 的人', 'किसी ऐसे को बुलाओ जिसे भी एक Lumi चाहिए', 'Invite quelqu’un qui a aussi besoin d’un Lumi'],

  // ── Mensajes de main.js ──
  ['Descargar en la App Store', 'Download on the App Store', '在 App Store 下载', 'App Store से डाउनलोड करो', 'Télécharger dans l’App Store'],
  ['Ya en el iPhone', 'Now on iPhone', '现已登陆 iPhone', 'अब iPhone पर', 'Disponible sur iPhone'],
  ['He encontrado una mascota que brilla cuando sueltas el móvil. Creo que tú también necesitas un Lumi.', 'I found a pet that shines when you put your phone down. I think you need a Lumi too.', '我发现了一只你放下手机就会发光的宠物。我觉得你也需要一个 Lumi。', 'मुझे एक पालतू मिला जो फ़ोन रखते ही चमकता है। मुझे लगता है तुम्हें भी एक Lumi चाहिए।', 'J’ai trouvé une mascotte qui brille quand tu poses ton téléphone. Je crois que toi aussi, tu as besoin d’un Lumi.'],
  ['Enlace copiado. Pégaselo a quien quieras.', 'Link copied. Paste it to whoever you like.', '链接已复制。发给你想分享的人吧。', 'लिंक कॉपी हो गया। जिसे चाहो भेज दो।', 'Lien copié. Colle-le à qui tu veux.'],
  ['Copia este enlace:', 'Copy this link:', '复制这个链接：', 'यह लिंक कॉपी करो:', 'Copie ce lien :'],
  ['Ese correo no parece completo. Revisa que tenga @ y dominio, por ejemplo tu@correo.com.', 'That email doesn’t look complete. Check it has an @ and a domain, for example you@email.com.', '这个邮箱地址好像不完整。请检查是否有 @ 和域名，例如 you@email.com。', 'यह ईमेल पूरा नहीं लगता। देखो कि उसमें @ और डोमेन है, जैसे you@email.com।', 'Cet e-mail semble incomplet. Vérifie qu’il a un @ et un domaine, par exemple toi@email.com.'],
  ['La lista de espera abre muy pronto y todavía no guarda correos. Vuelve en unos días y Lumi te apunta.', 'The waitlist opens very soon and doesn’t save emails yet. Come back in a few days and Lumi will sign you up.', '等候名单很快开放，目前还不能保存邮箱。过几天再来，Lumi 会帮你登记。', 'प्रतीक्षा सूची बहुत जल्द खुलेगी और अभी ईमेल सहेजती नहीं। कुछ दिनों में लौटो, Lumi तुम्हारा नाम लिख लेगी।', 'La liste d’attente ouvre très bientôt et n’enregistre pas encore les e-mails. Reviens dans quelques jours et Lumi t’inscrira.'],
  ['No se ha podido guardar tu correo. Comprueba la conexión y vuelve a intentarlo.', 'We couldn’t save your email. Check your connection and try again.', '无法保存你的邮箱。请检查网络后重试。', 'तुम्हारा ईमेल सहेजा नहीं जा सका। कनेक्शन देखकर फिर कोशिश करो।', 'Impossible d’enregistrer ton e-mail. Vérifie ta connexion et réessaie.'],

  // ── Página 404 ──
  ['Página no encontrada · Lumi', 'Page not found · Lumi', '找不到页面 · Lumi', 'पेज नहीं मिला · Lumi', 'Page introuvable · Lumi'],
  ['Esta página se ha ido de expedición', 'This page has gone on an expedition', '这个页面出去探险了', 'यह पेज सफ़र पर निकल गया है', 'Cette page est partie en expédition'],
  ['No la encontramos por aquí. Seguro que vuelve con una postal.', 'We can’t find it around here. It’ll surely come back with a postcard.', '我们在这里找不到它。它一定会带着明信片回来。', 'हमें यह यहाँ नहीं मिला। पक्का पोस्टकार्ड लेकर लौटेगा।', 'On ne la trouve pas par ici. Elle reviendra sûrement avec une carte postale.'],
  ['Volver al inicio', 'Back to home', '返回首页', 'होम पर लौटो', 'Retour à l’accueil'],

  // ── Páginas legales ──
  ['Última actualización:', 'Last updated:', '最后更新：', 'आख़िरी अपडेट:', 'Dernière mise à jour :'],
  ['¿Algo más?', 'Anything else?', '还有别的问题？', 'कुछ और?', 'Autre chose ?'],
  ['Escríbenos a', 'Write to us at', '写信给我们：', 'हमें लिखो:', 'Écris-nous à'],
];
