/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Lumi API
 * Cuentas, sesión y lista de espera de Lumi.
 * OpenAPI spec version: 1.0.0
 */
import { apiFetch } from './client';
export interface JoinWaitlistDto {
  email: string;
  /**
     * App que más le roba tiempo
     * @nullable
     */
  app?: string | null;
  /** @nullable */
  form?: string | null;
  /** @nullable */
  utm_source?: string | null;
  /** @nullable */
  utm_medium?: string | null;
  /** @nullable */
  utm_campaign?: string | null;
  /** @nullable */
  utm_content?: string | null;
  /** @nullable */
  ref?: string | null;
  /** @nullable */
  referrer?: string | null;
  /** @nullable */
  lang?: string | null;
}

export interface RegisterDto {
  email: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
  /** @maxLength 40 */
  name?: string;
  /** @maxLength 24 */
  lumiName?: string;
}

export interface UserDto {
  id: string;
  email: string;
  name: string;
  lumiName: string;
  emailVerified: boolean;
  createdAt: string;
}

export interface AuthSessionDto {
  /** JWT de acceso. Caduca en 15 minutos. */
  accessToken: string;
  /** Token de refresco opaco. Caduca en 30 días y se rota en cada uso. */
  refreshToken: string;
  /** Segundos hasta que caduca el token de acceso. */
  expiresIn: number;
  user: UserDto;
}

export interface LoginDto {
  email: string;
  password: string;
}

export interface RefreshDto {
  refreshToken: string;
}

export interface CodeDto {
  /** @pattern ^\d{6}$ */
  code: string;
}

export interface ForgotPasswordDto {
  email: string;
}

export interface ResetPasswordDto {
  email: string;
  /** @pattern ^\d{6}$ */
  code: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
}

export interface UpdateMeDto {
  /** @maxLength 40 */
  name?: string;
  /** @maxLength 24 */
  lumiName?: string;
}

export interface ChangePasswordDto {
  currentPassword: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  newPassword: string;
}

export interface DeleteAccountDto {
  /** Contraseña actual, para confirmar */
  password: string;
}

/**
 * @nullable
 */
export type ProgressDtoData = { [key: string]: unknown } | null;

export interface ProgressDto {
  /** @nullable */
  data: ProgressDtoData;
  /** @nullable */
  updatedAt: string | null;
}

/**
 * Progreso de la app tal cual (el servidor no lo interpreta)
 */
export type SaveProgressDtoData = { [key: string]: unknown };

export interface SaveProgressDto {
  /** Progreso de la app tal cual (el servidor no lo interpreta) */
  data: SaveProgressDtoData;
}

export type HealthCheck200 = {
  status?: string;
};

export const getHealthCheckUrl = () => {




  return `/health`
}

export const healthCheck = async ( options?: Parameters<typeof apiFetch>[1]): Promise<HealthCheck200> => {

  return apiFetch<HealthCheck200>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getJoinWaitlistUrl = () => {




  return `/waitlist`
}

export const joinWaitlist = async (joinWaitlistDto: JoinWaitlistDto, options?: Parameters<typeof apiFetch>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<void>(getJoinWaitlistUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(joinWaitlistDto)
  }
);}



export const getRegisterUrl = () => {




  return `/auth/register`
}

export const register = async (registerDto: RegisterDto, options?: Parameters<typeof apiFetch>[1]): Promise<AuthSessionDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<AuthSessionDto>(getRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerDto)
  }
);}



export const getLoginUrl = () => {




  return `/auth/login`
}

export const login = async (loginDto: LoginDto, options?: Parameters<typeof apiFetch>[1]): Promise<AuthSessionDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<AuthSessionDto>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginDto)
  }
);}



export const getRefreshUrl = () => {




  return `/auth/refresh`
}

export const refresh = async (refreshDto: RefreshDto, options?: Parameters<typeof apiFetch>[1]): Promise<AuthSessionDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<AuthSessionDto>(getRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(refreshDto)
  }
);}



export const getLogoutUrl = () => {




  return `/auth/logout`
}

export const logout = async (refreshDto: RefreshDto, options?: Parameters<typeof apiFetch>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<void>(getLogoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(refreshDto)
  }
);}



export const getVerifyEmailUrl = () => {




  return `/auth/verify-email`
}

export const verifyEmail = async (codeDto: CodeDto, options?: Parameters<typeof apiFetch>[1]): Promise<UserDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<UserDto>(getVerifyEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(codeDto)
  }
);}



export const getResendVerificationUrl = () => {




  return `/auth/verify-email/resend`
}

export const resendVerification = async ( options?: Parameters<typeof apiFetch>[1]): Promise<void> => {

  return apiFetch<void>(getResendVerificationUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getForgotPasswordUrl = () => {




  return `/auth/forgot-password`
}

export const forgotPassword = async (forgotPasswordDto: ForgotPasswordDto, options?: Parameters<typeof apiFetch>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<void>(getForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(forgotPasswordDto)
  }
);}



export const getResetPasswordUrl = () => {




  return `/auth/reset-password`
}

export const resetPassword = async (resetPasswordDto: ResetPasswordDto, options?: Parameters<typeof apiFetch>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<void>(getResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(resetPasswordDto)
  }
);}



export const getGetMeUrl = () => {




  return `/me`
}

export const getMe = async ( options?: Parameters<typeof apiFetch>[1]): Promise<UserDto> => {

  return apiFetch<UserDto>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUpdateMeUrl = () => {




  return `/me`
}

export const updateMe = async (updateMeDto: UpdateMeDto, options?: Parameters<typeof apiFetch>[1]): Promise<UserDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<UserDto>(getUpdateMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateMeDto)
  }
);}



export const getChangePasswordUrl = () => {




  return `/me/password`
}

export const changePassword = async (changePasswordDto: ChangePasswordDto, options?: Parameters<typeof apiFetch>[1]): Promise<AuthSessionDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<AuthSessionDto>(getChangePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(changePasswordDto)
  }
);}



export const getDeleteAccountUrl = () => {




  return `/me/delete`
}

export const deleteAccount = async (deleteAccountDto: DeleteAccountDto, options?: Parameters<typeof apiFetch>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<void>(getDeleteAccountUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(deleteAccountDto)
  }
);}



export const getGetProgressUrl = () => {




  return `/me/progress`
}

export const getProgress = async ( options?: Parameters<typeof apiFetch>[1]): Promise<ProgressDto> => {

  return apiFetch<ProgressDto>(getGetProgressUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getSaveProgressUrl = () => {




  return `/me/progress`
}

export const saveProgress = async (saveProgressDto: SaveProgressDto, options?: Parameters<typeof apiFetch>[1]): Promise<ProgressDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return apiFetch<ProgressDto>(getSaveProgressUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(saveProgressDto)
  }
);}
